import { useEffect, useState } from 'react';
import { ArrowLeft, CalendarCheck, Check, Plus, Save, Trash2 } from 'lucide-react';
import type { BuilderSet, Catalog, Movie, Rotation, Viewer } from '../shared/types';
import { localToday } from '../shared/identity';
import { api } from './api';
import { Action, Empty } from './components';
import { FilmPicker } from './FilmPicker';
import { TurnFields } from './TurnFields';
export function BuilderScreen({catalog,viewer,rotation,onMovie,onPublished}: {catalog: Catalog; viewer: Viewer | null; rotation: Rotation | null; onMovie: (m: Movie) => void; onPublished: () => void}) {
  const [sets,setSets] = useState<BuilderSet[]>([]), [editing,setEditing] = useState<BuilderSet | null>(null), [creating,setCreating] = useState(false);
  const [title,setTitle] = useState(''), [notes,setNotes] = useState(''), [films,setFilms] = useState<Movie[]>([]);
  const [error,setError] = useState(''), [status,setStatus] = useState(''), [busy,setBusy] = useState(false), [loading,setLoading] = useState(true);
  const [publishing,setPublishing] = useState(false), [date,setDate] = useState(localToday()), [complete,setComplete] = useState(Boolean(rotation)), [cycle,setCycle] = useState(rotation?.cycle_id ?? ''), [slot,setSlot] = useState<number | null>(rotation?.nominal_slot ?? 1), [swap,setSwap] = useState('');
  const load = async () => { try { setSets(await api.builders()); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load Builder.'); } finally { setLoading(false); } };
  useEffect(() => { if (viewer) void load(); },[viewer?.id]);
  if (!viewer) return <Empty title="Builder is personal">Local demo bypass has no signed-in owner. Use a member session to plan privately.</Empty>;
  const open = (set?: BuilderSet) => { setEditing(set ?? null); setCreating(!set); setTitle(set?.title ?? ''); setNotes(set?.notes ?? ''); setFilms((set?.movie_ids ?? []).map(id => catalog.movies.find(m => m.id === id)!).filter(Boolean)); setPublishing(false); setError(''); setStatus(''); };
  const run = async (work: () => Promise<void>) => { setBusy(true); setError(''); setStatus(''); try { await work(); } catch (e) { setError(e instanceof Error ? e.message : 'Action failed.'); } finally { setBusy(false); } };
  const save = async () => { const saved = await api.saveBuilder({title,notes,movie_ids: films.map(m => m.id),...(editing ? {revision: editing.revision} : {})},editing?.id); setEditing(saved); setCreating(false); await load(); return saved; };
  const nominal = catalog.members.find(m => m.sort_order === slot);
  const offTurn = slot !== null && slot <= 4 && nominal?.id !== viewer.id;
  const inEditor = creating || editing;
  return <div className="stack"><p className="meta">Only you can access these unpublished sets. Administrators cannot inspect them.</p>{!inEditor ? <><Action icon={Plus} onClick={() => open()}>New set</Action>{loading && <p role="status">Loading your sets…</p>}<div className="history-grid">{sets.map(set => <article className="card stack" key={set.id}><h2>{set.title || 'Untitled set'}</h2><p className="meta">{set.movie_ids.length} films · Planned {new Date(set.created_at).toLocaleDateString('en-AU')}</p>{set.notes && <p className="meta">{set.notes}</p>}<Action icon={ArrowLeft} onClick={() => open(set)}>Open set</Action></article>)}</div>{!loading && !sets.length && <Empty title="Your next night starts here">Keep several ideas, then publish one when it is ready.</Empty>}</> : publishing && editing ? <section className="card stack" aria-labelledby="publish-heading"><h2 id="publish-heading">Publish {editing.title || 'this set'}?</h2><p className="meta">{films.length} films in the saved order. Your original planning date stays in History. This set will leave Builder. Its title and note will become visible to the club.</p>{editing.notes && <p className="meta">Note: {editing.notes}</p>}<label className="input-label">Actual event date<input autoFocus type="date" className="field__input" required value={date} onChange={e => setDate(e.target.value)} /></label><TurnFields catalog={catalog} rotation={rotation} complete={complete} onComplete={setComplete} cycle={cycle} onCycle={setCycle} slot={slot} onSlot={setSlot} />
      <p className="meta">Actual host: {slot === 5 ? 'CLSC · hostless' : viewer.display_name.toUpperCase()}</p>{offTurn && <p className="notice" role="status">This is {nominal?.display_name.toUpperCase() ?? 'another member'}’s nominal turn. Publishing records you as the actual host. Explain the swap; only current-turn completion advances rotation.</p>}{slot !== 5 && <label className="input-label">Swap explanation {offTurn ? '(required)' : '(optional)'}<textarea className="field__input" maxLength={2000} required={Boolean(offTurn)} value={swap} onChange={e => setSwap(e.target.value)} /></label>}{complete && slot === 5 && <p className="notice">This completes Classics, marks all four members Seen for the lineup and returns rotation to slot 1 awaiting a new cycle.</p>}
      <div className="button-set"><Action icon={Check} intent="constructive" disabled={busy || !date || !slot || Boolean(offTurn && !swap.trim())} onClick={() => void run(async () => { await api.publishBuilder(editing.id,{revision: editing.revision,event_date: date,cycle_id: cycle === 'new' ? null : cycle || null,cycle_slot: slot!,complete_turn: complete,...(complete ? {turn_version: rotation?.version} : {}),swap_note: swap,...(cycle === 'new' ? {new_cycle: {rough_date: date}} : {})}); onPublished(); })}>{busy ? 'Publishing…' : 'Confirm publication'}</Action><Action icon={ArrowLeft} disabled={busy} onClick={() => setPublishing(false)}>Back to set</Action></div></section> : <><div className="button-set"><Action icon={ArrowLeft} disabled={busy} onClick={() => { setEditing(null); setCreating(false); }}>All sets</Action><Action icon={Save} disabled={busy} onClick={() => void run(async () => { await save(); setStatus('Private set saved.'); })}>Save set</Action><Action icon={CalendarCheck} disabled={busy || !films.length} onClick={() => void run(async () => { await save(); setDate(localToday()); setComplete(Boolean(rotation)); setCycle(rotation?.cycle_id ?? ''); setSlot(rotation?.nominal_slot ?? 1); setSwap(''); setPublishing(true); })}>Publish</Action>{editing && <Action icon={Trash2} disabled={busy} onClick={() => { if (window.confirm('Permanently delete this private set?')) void run(async () => { await api.deleteBuilder(editing.id,editing.revision); setEditing(null); setCreating(false); await load(); }); }}>Delete set</Action>}</div><section className="card stack"><label className="input-label">Private title (optional)<input className="field__input" maxLength={300} value={title} disabled={busy} onChange={e => setTitle(e.target.value)} /></label><label className="input-label">Private note (optional)<textarea className="field__input" maxLength={10000} value={notes} disabled={busy} onChange={e => setNotes(e.target.value)} /></label></section><FilmPicker selected={films} onSelected={setFilms} onMovie={onMovie} disabled={busy} /></>}{status && <p role="status">{status}</p>}{error && <p className="error-message" role="alert">{error}</p>}</div>;
}
