import { useEffect, useState } from 'react';
import { Check, CircleHelp, History, Library, RefreshCw, X } from 'lucide-react';
import { latestScores, requiredScores } from '../shared/ranking';
import type { Member, MovieDetail } from '../shared/types';
import { api } from './api';
import { Action, eventDateLabel, Empty, Failure, Poster, RankingScore, LoadingView, RouteLink } from './components';

export function DetailScreen({id,members,answer,writesEnabled,onMovie}: {id: string; members: Member[]; answer: (m: string,p: string,s: boolean | null) => Promise<MovieDetail>; writesEnabled: boolean; onMovie: (m: MovieDetail) => void}) {
  const [movie,setMovie] = useState<MovieDetail | null>(null), [error,setError] = useState(''), [busy,setBusy] = useState(false);
  const [retry,setRetry] = useState(0), [loading,setLoading] = useState(true);
  const [status,setStatus] = useState('');
  const update = (m: MovieDetail) => { setMovie(m); onMovie(m); };
  const work = async (task: () => Promise<void>) => { setBusy(true); setError(''); setStatus(''); try { await task(); } catch (e) { setError(e instanceof Error ? e.message : 'Action failed.'); } finally { setBusy(false); } };
  useEffect(() => { let active = true; setLoading(true); setError(''); api.detail(id).then(m => { if (active) setMovie(m); }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; },[id,retry]);
  if (loading && !movie) return <LoadingView label="Loading film details…" />;
  if (!movie) return <Failure message={error} retry={() => setRetry(r => r+1)} />;
  const backdrop = movie.assets.find(a => a.asset_type === 'backdrop');
  return <div className="stack">{error && <div role="alert" className="refresh-failure">{error}<Action icon={RefreshCw} onClick={() => setRetry(r => r+1)}>Retry film load</Action></div>}{loading && <p role="status">Refreshing film details…</p>}{backdrop && <img className="film-backdrop" src={backdrop.reference} alt="" onError={e => { e.currentTarget.hidden = true; }} />}
    <section className="card detail-header"><Poster movie={movie} large /><div><h2>{movie.title}</h2>{movie.original_title && movie.original_title !== movie.title && <p>Original title: {movie.original_title}</p>}<p>{movie.year ?? 'Year unknown'} · {movie.runtime ? `${movie.runtime} min` : 'Runtime unknown'}</p><p className="meta">Release: {movie.release_date ?? 'Not recorded'}</p><p>{movie.genres.join(' · ') || 'Genres not recorded'}</p><p>{movie.overview || 'No overview available yet.'}</p><span className="badge">{movie.classic ? 'Classics candidate' : 'Outside Classics pool'}</span></div></section>
    <div className="detail-grid"><section className="card stack"><h2>Seen It?</h2>{members.map(member => { const state = movie.seen.find(s => s.member_id === member.id); return <div className="member-state" key={member.id}><div><strong>{member.display_name.toUpperCase()}{!member.active ? ' (inactive)' : ''}</strong><p className="meta">{state ? state.seen ? 'Seen' : 'Not seen' : 'Unknown'}</p>{state && <small>Updated {new Date(state.updated_at).toLocaleString('en-AU')}</small>}</div><div className="button-set">{[{value: true,label: 'Yes',icon: Check},{value: false,label: 'No',icon: X},{value: null,label: 'Unknown',icon: CircleHelp}].map(option => <Action key={option.label} icon={option.icon} aria-label={`Set ${member.display_name.toUpperCase()} to ${option.label}`} aria-pressed={option.value === null ? !state : Boolean(state) && state!.seen === Number(option.value)} disabled={busy || !writesEnabled || !member.active} onClick={() => {
      setBusy(true); setError(''); answer(id,member.id,option.value).then(setMovie).catch(e => setError(e.message)).finally(() => setBusy(false));
    }}>{option.label}</Action>)}</div></div>; })}</section>
    <div className="stack">{movie.ranking && <section className="stack"><h2>Classics score</h2><RankingScore movie={movie} /></section>}<section className="stack"><h2>Ratings</h2>{movie.scores.length ? latestScores(movie.scores).map((s,i) => <div className="source-record" key={`${s.provider}-${s.metric}-${i}`}><strong>{s.provider} · {s.metric}</strong>{requiredScores.some(key => key === `${s.provider}:${s.metric}`) && <span className="badge">Classics input</span>}<p>{s.raw_value} / {s.raw_scale ?? 'scale not supplied'}{s.normalized_value !== null ? ` · normalised ${s.normalized_value.toFixed(1)}` : ''}</p><details><summary>Source & capture details</summary><p className="meta">{s.vote_count !== null ? `${s.vote_count.toLocaleString()} votes · ` : ''}Via {s.retrieved_via ?? 'unspecified'} · Captured {new Date(s.fetched_at).toLocaleString('en-AU')}</p></details></div>) : <p className="meta">No source scores stored. Refresh after identifying this film.</p>}</section></div></div>
    <section className="card stack"><div className="section-title"><h2>Book Club appearances</h2><RouteLink to="history" icon={History}>History</RouteLink></div>{movie.appearances.map((a,i) => <p key={`${a.id}-${i}`}>{eventDateLabel(a)} · {a.title || 'Book Club night'} · film {a.position}</p>)}{!movie.appearances.length && <Empty title="Not watched at Book Club yet">This film has no recorded event appearances.</Empty>}</section>
    <details className="utility-disclosure"><summary>Classics membership & score maintenance</summary>    <section className="card stack"><div className="button-set"><Action icon={Library} disabled={busy || !writesEnabled} onClick={() => void work(async () => update(await api.classic(id,!movie.classic)))}>{movie.classic ? 'Remove from Classics' : 'Add to Classics'}</Action><Action icon={RefreshCw} disabled={busy || !writesEnabled || !movie.external_ids.some(e => ['imdb','tmdb'].includes(e.provider))} onClick={() => void work(async () => { const result = await api.refreshScores(id); update(result.movie); setStatus(result.providers.map(p => `${p.provider}: ${p.message}${p.retryAfter !== undefined ? ` Retry after ${p.retryAfter}s.` : ''}`).join(' ')); })}>{busy ? 'Working…' : 'Refresh scores'}</Action></div>{movie.classics_membership && <p className="meta">Added {new Date(movie.classics_membership.added_at).toLocaleDateString('en-AU')} · {movie.classics_membership.source ?? 'Source unknown'}</p>}{status && <p role="status">{status}</p>}{error && <p role="alert" className="error-message">{error}</p>}</section>
</details>
    <details className="utility-disclosure"><summary>Technical identifiers & artwork</summary>    <section className="card stack"><h2>External identifiers & artwork</h2>{movie.external_ids.map(e => <p key={e.provider}>{e.provider}: <span className="numeric">{e.external_id}</span></p>)}{!movie.external_ids.length && <p className="meta">No external IDs recorded.</p>}{movie.assets.map(a => <p className="meta" key={a.reference}>{a.provider} · {a.asset_type} · {a.preferred ? 'preferred' : 'alternate'} · {a.width && a.height ? `${a.width} × ${a.height}` : 'dimensions unknown'}</p>)}</section>
</details>
  </div>;
}
