import { useEffect, useState } from 'react';
import { Check, CircleHelp, History, X } from 'lucide-react';
import type { Member, MovieDetail } from '../shared/types';
import { api } from './api';
import { Action, dateLabel, Empty, Failure, Poster, RankingCard, RouteLink } from './components';

export function DetailScreen({id,members,answer,writesEnabled}: {id: string; members: Member[]; answer: (m: string,p: string,s: boolean | null) => Promise<MovieDetail>; writesEnabled: boolean}) {
  const [movie,setMovie] = useState<MovieDetail | null>(null), [error,setError] = useState(''), [busy,setBusy] = useState(false);
  const [retry,setRetry] = useState(0), [loading,setLoading] = useState(true);
  useEffect(() => { let active = true; setLoading(true); setError(''); api.detail(id).then(m => { if (active) setMovie(m); }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; },[id,retry]);
  if (loading) return <div className="loading-state" role="status">Loading film details…</div>;
  if (!movie) return <Failure message={error} retry={() => setRetry(r => r+1)} />;
  const backdrop = movie.assets.find(a => a.asset_type === 'backdrop');
  return <div className="stack">{backdrop && <img className="film-backdrop" src={backdrop.reference} alt="" onError={e => { e.currentTarget.hidden = true; }} />}
    <section className="card detail-header"><Poster movie={movie} large /><div><p className="eyebrow">THE FILM</p><h2>{movie.title}</h2>{movie.original_title && movie.original_title !== movie.title && <p>Original title: {movie.original_title}</p>}<p>{movie.year ?? 'Year unknown'} · {movie.runtime ? `${movie.runtime} min` : 'Runtime unknown'}</p><p className="meta">Release: {movie.release_date ?? 'Not recorded'}</p><p>{movie.genres.join(' · ') || 'Genres not recorded'}</p><p>{movie.overview || 'No overview available yet.'}</p><span className="badge">{movie.classic ? 'Classics candidate' : 'Outside Classics pool'}</span></div></section>
    <div className="detail-grid"><section className="card stack"><h2>Seen It?</h2>{members.map(member => { const state = movie.seen.find(s => s.member_id === member.id); return <div className="member-state" key={member.id}><div><strong>{member.display_name}{!member.active ? ' (inactive)' : ''}</strong><p className="meta">{state ? state.seen ? 'Seen' : 'Not seen' : 'Unknown'}</p>{state && <small>Updated {new Date(state.updated_at).toLocaleString('en-AU')}</small>}</div><div className="button-set">{[{value: true,label: 'Yes',icon: Check},{value: false,label: 'No',icon: X},{value: null,label: 'Unknown',icon: CircleHelp}].map(option => <Action key={option.label} icon={option.icon} aria-label={`Set ${member.display_name} to ${option.label}`} aria-pressed={option.value === null ? !state : Boolean(state) && state!.seen === Number(option.value)} disabled={busy || !writesEnabled || !member.active} onClick={() => {
      setBusy(true); setError(''); answer(id,member.id,option.value).then(setMovie).catch(e => setError(e.message)).finally(() => setBusy(false));
    }}>{option.label}</Action>)}</div></div>; })}{error && <p className="error-message" role="alert">{error}</p>}</section>
    <div className="stack">{movie.ranking && <RankingCard movie={movie} />}<section className="card stack"><h2>Source ratings</h2>{movie.scores.length ? movie.scores.map((s,i) => <div className="source-record" key={`${s.provider}-${s.metric}-${i}`}><strong>{s.provider} · {s.metric}</strong><p>{s.raw_value} / {s.raw_scale ?? 'scale not supplied'}{s.normalized_value !== null ? ` · normalised ${s.normalized_value.toFixed(1)}` : ''}</p><p className="meta">{s.vote_count !== null ? `${s.vote_count.toLocaleString()} votes · ` : ''}Captured {new Date(s.fetched_at).toLocaleString('en-AU')}</p></div>) : <p className="meta">No source scores stored. A future explicit refresh can capture new snapshots.</p>}</section></div></div>
    <section className="card stack"><h2>External identifiers & artwork</h2>{movie.external_ids.map(e => <p key={e.provider}>{e.provider}: <span className="numeric">{e.external_id}</span></p>)}{!movie.external_ids.length && <p className="meta">No external IDs recorded.</p>}{movie.assets.map(a => <p className="meta" key={a.reference}>{a.provider} · {a.asset_type} · {a.preferred ? 'preferred' : 'alternate'} · {a.width && a.height ? `${a.width} × ${a.height}` : 'dimensions unknown'}</p>)}</section>
    <section className="card stack"><div className="section-title"><h2>Book Club appearances</h2><RouteLink to="history" icon={History}>History</RouteLink></div>{movie.appearances.map((a,i) => <p key={`${a.id}-${i}`}>{dateLabel(a.event_date)} · {a.title || 'Book Club night'} · film {a.position}</p>)}{!movie.appearances.length && <Empty title="Not watched at Book Club yet">This film has no recorded event appearances.</Empty>}</section>
  </div>;
}
