import { useRef, useState, type FormEvent } from 'react';
import { ArrowDown, ArrowUp, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import type { Movie, SearchResponse } from '../shared/types';
import { api } from './api';
import { Action, Empty, MovieRow } from './components';
export function FilmPicker({selected,onSelected,onMovie,disabled = false}: {selected: Movie[]; onSelected: (films: Movie[]) => void; onMovie: (movie: Movie) => void; disabled?: boolean}) {
  const [query,setQuery] = useState(''), [results,setResults] = useState<SearchResponse | null>(null);
  const [title,setTitle] = useState(''), [year,setYear] = useState(''), [runtime,setRuntime] = useState('');
  const [error,setError] = useState(''), [busy,setBusy] = useState(false), [searching,setSearching] = useState(false);
  const generation = useRef(0);
  const add = (movie: Movie) => onSelected([...selected,movie]);
  const run = async (work: () => Promise<void>) => { setBusy(true); setError(''); try { await work(); } catch (e) { setError(e instanceof Error ? e.message : 'Action failed.'); } finally { setBusy(false); } };
  const search = async (e: FormEvent) => {
    e.preventDefault(); const current = ++generation.current; setSearching(true); setError('');
    try { const data = await api.search(query.trim()); if (current === generation.current) setResults(data); }
    catch (e) { if (current === generation.current) setError(e instanceof Error ? e.message : 'Search failed.'); }
    finally { if (current === generation.current) setSearching(false); }
  };
  const move = (index: number,offset: number) => { const next = [...selected]; [next[index],next[index+offset]] = [next[index+offset],next[index]]; onSelected(next); };
  return <div className="stack"><section className="card stack"><h2>Find a film</h2><form className="stack" onSubmit={search}><label className="input-label">Search saved films & TMDB<input className="field__input" value={query} maxLength={150} required onChange={e => setQuery(e.target.value)} /></label><Action type="submit" icon={Search} disabled={searching || disabled}>{searching ? 'Searching…' : 'Search'}</Action></form>
    {results && <div className="stack"><p className="meta" role="status">{results.lookup.message ?? 'Selecting a TMDB film saves its metadata.'}</p>{results.local.map(m => <div className="search-row" key={m.id}><MovieRow movie={m} /><Action icon={Plus} aria-label={`Add ${m.title}`} disabled={busy || disabled} onClick={() => add(m)} /></div>)}{results.external.map(m => <div className="search-row" key={m.externalId}><div className="movie-copy"><strong>{m.title}</strong><p className="meta">{m.year ?? 'Year unknown'} · TMDB</p></div><Action icon={Plus} aria-label={`Import and add ${m.title}`} disabled={busy || disabled} onClick={() => void run(async () => { const movie = await api.importMovie(m.externalId); onMovie(movie); add(movie); })} /></div>)}{!results.local.length && !results.external.length && <Empty title="No matching films">Try another title or add it manually.</Empty>}</div>}
    <details><summary><Pencil size={18} aria-hidden="true" />Add a film manually</summary><form className="stack manual-form" onSubmit={e => { e.preventDefault(); void run(async () => { const movie = await api.createMovie({title,...(year ? {year: Number(year)} : {}),...(runtime ? {runtime: Number(runtime)} : {})}); onMovie(movie); add(movie); setTitle(''); setYear(''); setRuntime(''); }); }}><label className="input-label">Film title<input required className="field__input" maxLength={300} value={title} onChange={e => setTitle(e.target.value)} /></label><div className="two-fields"><label className="input-label">Year<input type="number" className="field__input" min={1870} max={2200} value={year} onChange={e => setYear(e.target.value)} /></label><label className="input-label">Runtime (min)<input type="number" className="field__input" min={1} max={10000} value={runtime} onChange={e => setRuntime(e.target.value)} /></label></div><Action type="submit" icon={Plus} disabled={busy || disabled}>Create & add film</Action></form></details>
  </section><section className="card stack"><h2>Lineup · {selected.length} films</h2><p className="meta">Viewing order matters. Add as many films as the night calls for.</p>{!selected.length && <Empty title="No films selected">Search or create a film above.</Empty>}<ol className="lineup-list">{selected.map((movie,i) => <li key={`${movie.id}-${i}`}><MovieRow movie={movie}><span className="meta">Viewing position {i+1}</span></MovieRow><div className="button-set"><Action icon={ArrowUp} aria-label={`Move ${movie.title} earlier`} disabled={i === 0 || disabled || busy} onClick={() => move(i,-1)} /><Action icon={ArrowDown} aria-label={`Move ${movie.title} later`} disabled={i === selected.length-1 || disabled || busy} onClick={() => move(i,1)} /><Action icon={Trash2} aria-label={`Remove ${movie.title}`} disabled={disabled || busy} onClick={() => onSelected(selected.filter((_,j) => i !== j))} /></div></li>)}</ol></section>{error && <p role="alert" className="error-message">{error}</p>}</div>;
}
