import { useState } from 'react';
import { CalendarPlus, History, Pencil, Trash2 } from 'lucide-react';
import { api } from './api';
import type { Session, HistoryAudit, Catalog } from '../shared/types';
import { Action, RouteLink, dateLabel, Empty, SessionCard } from './components';
export function HistoryScreen({catalog,onChanged}: {catalog: Catalog; onChanged: () => void}) {
  const [host,setHost] = useState('all');
  const visible = catalog.sessions.filter(s => host === 'all' || (host === 'classics' ? s.kind === 'classics' : s.host_member_id === host));
  return <div className="stack"><div className="archive-tools"><label className="input-label">Jump to cycle<select className="field__input" defaultValue="" onChange={e => { document.getElementById(`cycle-${e.target.value}`)?.scrollIntoView(); e.target.value = ''; }}><option value="">Choose cycle</option>{catalog.cycles.filter(c => visible.some(s => s.cycle_id === c.id)).map(c => <option key={c.id} value={c.id}>{c.title || `Cycle ${c.ordinal}`}</option>)}</select></label><label className="input-label">Actual host<select className="field__input" value={host} onChange={e => setHost(e.target.value)}><option value="all">All hosts</option>{catalog.members.map(m => <option key={m.id} value={m.id}>{m.display_name.toUpperCase()}</option>)}<option value="classics">CLSC</option></select></label></div><RouteLink to="event" icon={CalendarPlus}>Create an event</RouteLink>{catalog.cycles.filter(c => visible.some(s => s.cycle_id === c.id)).map(cycle => <section className="stack" key={cycle.id} id={`cycle-${cycle.id}`}>
    <h2>{cycle.title || `Cycle ${cycle.ordinal}`}</h2><p className="meta">Cycle anchor: {dateLabel(cycle.rough_date)} · Nominal slot order</p>
    <div className="history-grid">{visible.filter(s => s.cycle_id === cycle.id).sort((a,b) => (a.cycle_slot ?? 6)-(b.cycle_slot ?? 6) || a.id.localeCompare(b.id)).map(s => <HistoryEvent key={s.id} session={s} catalog={catalog} onChanged={onChanged} />)}</div>
  </section>)}{visible.some(s => !s.cycle_id) && <section className="stack"><h2>Ungrouped events</h2><div className="history-grid">{visible.filter(s => !s.cycle_id).map(s => <HistoryEvent key={s.id} session={s} catalog={catalog} onChanged={onChanged} />)}</div></section>}
    {catalog.sessions.length > 0 && !visible.length && <Empty title="No events for this host">Choose another host or All hosts.</Empty>}{!catalog.sessions.length && <Empty title="No events yet">Create an event to begin your journal.</Empty>}</div>;
}

function HistoryEvent({session,catalog,onChanged}: {session: Session; catalog: Catalog; onChanged: () => void}) {
  const [auditOpen,setAuditOpen] = useState(false);
  const [audit,setAudit] = useState<HistoryAudit[] | null>(null), [error,setError] = useState(''), [busy,setBusy] = useState(false);
  const run = async (work: () => Promise<void>) => { setBusy(true); setError(''); try { await work(); } catch(e) { setError(e instanceof Error ? e.message : 'Action failed.'); } finally { setBusy(false); } };
  return <div className="stack"><SessionCard session={session} members={catalog.members} /><div className="button-set"><RouteLink to={`event/${session.id}`} icon={Pencil} variant="secondary">Edit</RouteLink><Action icon={History} variant="tertiary" aria-expanded={auditOpen} aria-controls={`audit-${session.id}`} disabled={busy && !auditOpen} onClick={() => { setAuditOpen(!auditOpen); if (!auditOpen && !audit) void run(async () => setAudit(await api.audit(session.id))); }}>Audit</Action><Action icon={Trash2} variant="danger" disabled={busy} onClick={() => { if (window.confirm('Remove this event from History? An administrator can restore it. Rotation will remain unchanged.')) void run(async () => { await api.deleteSession(session.id); onChanged(); }); }}>Delete</Action></div>
    {auditOpen && <section id={`audit-${session.id}`} className="audit-inline stack" aria-label="Event audit"><h3>Changes to this event</h3>{audit && !audit.length && <p className="meta">No application changes recorded. Legacy imports predate this audit trail.</p>}{audit?.map(row => {
      const changes = JSON.parse(row.changes_json) as {before?: {event_date?: string; title?: string; notes?: string}; after?: {event_date?: string; title?: string; notes?: string; movie_ids?: string[]; swap_note?: string}; rotation_unchanged?: boolean; requires_rotation_review?: boolean};
      return <div className="source-record" key={row.id}><p>{row.action.replaceAll('_',' ')} · {catalog.members.find(m => m.id === row.actor_member_id)?.display_name.toUpperCase() ?? 'LOCAL DEMO'}</p><p className="meta">{new Date(row.occurred_at).toLocaleString('en-AU')}</p>{changes.after && <p className="meta">{changes.before?.event_date && `${changes.before.event_date} → `}{changes.after.event_date} · {changes.after.title || 'Untitled'} · {changes.after.movie_ids?.map(id => catalog.movies.find(m => m.id === id)?.title ?? 'Film').join(', ')}</p>}<details><summary>Full change evidence</summary><pre className="audit-evidence">{JSON.stringify(changes,null,2)}</pre></details>{changes.after?.swap_note && <p className="meta">Swap: {changes.after.swap_note}</p>}{changes.rotation_unchanged && <p className="meta">Rotation unchanged.</p>}{changes.requires_rotation_review && <p className="meta">This event completed a turn. An administrator should review rotation if correction is needed.</p>}</div>;
    })}</section>}{error && <p className="error-message" role="alert">{error}</p>}</div>;
}
