import { formatCount } from '../shared/format';
import type { CallEstimate, Operation } from './maintenance-estimates';
const descriptions:Record<Operation,{scope:string;apis:string;collects:string;safeguards:string}>={
  missing:{scope:'Missing required ranking scores in Classics and active History. Confirmed negative availability checks are skipped; usable scores are retained.',apis:'MDBList, with conditional OMDb and TMDB fallback.',collects:'Absent IMDb, RT audience/critic, Letterboxd, Metacritic critic and TMDB ranking evidence; supported informational ratings and provider enrichment from the same responses. OMDb fallback can update title, year, runtime, director and genres. Score history is preserved.',safeguards:'10 films per BookClub batch; MDBList groups IMDb/TMDB identities. Partial batches allow one single-film recovery per omitted film. OMDb primary/secondary credentials have independent cooldowns. Provider failures and persisted header-driven cooldowns stop work.'},
  refresh:{scope:'Recheck identified films in Classics and active History, including previously unavailable scores.',apis:'MDBList, with conditional OMDb and TMDB fallback.',collects:'New provider score snapshots and supported same-response enrichment; OMDb fallback can update canonical metadata. Existing score history is retained.',safeguards:'10 films per BookClub batch; up to two MDBList identity groups, with single-film partial-batch recovery. OMDb supports primary/secondary failover and independent cooldowns. TMDB uses one detail request per fallback film. Provider failures/cooldowns stop work.'},
  metadata:{scope:'All catalogue films with valid IMDb identity, regardless of History/Classics membership. Missing IMDb identities are skipped.',apis:'OMDb.',collects:'Provider title evidence, canonical year, runtime, director and genres when supplied. Scores and History are preserved.',safeguards:'10 films per BookClub batch; one ordinary detail request per film, up to two with primary/secondary credential failover. Independent credential cooldowns. Browser checkpoint supports Stop, resume and discard.'},
  'tmdb-metadata':{scope:'Valid TMDB identities that are unchecked, stale after 150 days, or missing unchecked artwork. Missing director affects priority, not eligibility. Missing identities and already-checked films are skipped.',apis:'TMDB.',collects:'Canonical title evidence, original title, year/release date, runtime, overview, director, genres, poster/backdrop references and check timestamps; supported same-response enrichment. History and score history are preserved.',safeguards:'2 films per selected BookClub batch; one upstream details call per film. Persisted Retry-After/header cooldowns; no fixed daily quota is assumed. Resume uses refreshed eligibility, without a browser checkpoint.'},
  tmdb:{scope:'Refresh all catalogue films with valid TMDB identities, regardless of metadata freshness. Missing identities are skipped.',apis:'TMDB.',collects:'Provider title/scalars, countries, languages, production companies, top-15 cast and selected crew, keywords, US/AU certification evidence and Australian watch availability (subscription, free, ads, rent, buy). Canonical title reconciliation; other canonical metadata and scores are preserved.',safeguards:'2 films per BookClub batch; one appended details request per film. Persisted Retry-After/header cooldowns; no fixed daily quota is assumed. Browser checkpoint supports Stop, resume and discard.'},
  mdblist:{scope:'Refresh all catalogue films with supported identity: valid IMDb preferred, otherwise TMDB. Missing identities are skipped.',apis:'MDBList.',collects:'Provider title/runtime, safe identity claims and keywords. Canonical title reconciliation. Regionless stream/watch fields are excluded; this operation does not save ratings.',safeguards:'10 films per BookClub batch; one upstream batch call per IMDb/TMDB identity group present (up to two). Safety reserve: 25 requests. Provider quota headers are shown when supplied; persisted cooldowns stop work. Browser checkpoint supports Stop, resume and discard.'},
};
export function MaintenanceOperationDetails({operation,estimate}: {operation:Operation;estimate:CallEstimate}) {
  const details=descriptions[operation];
  return <div className="maintenance-details"><p className="meta"><strong>Scope: </strong>{details.scope}</p><p className="meta"><strong>APIs: </strong>{details.apis}</p><p className="meta"><strong>Estimated calls: </strong>{formatCount(estimate.eligible)} in-scope films · {formatCount(estimate.batches)} BookClub batches. {estimate.calls.map(call=>`${call.provider}: ${call.min===call.max ? formatCount(call.min) : `${formatCount(call.min)}–${formatCount(call.max)}`}`).join(' · ')}.</p><p className="meta">Assumes configured providers without active cooldowns.{(operation==='missing' || operation==='refresh') && ' Score ranges include recovery/failover; negative checks may reduce fallback calls.'}</p><details className="utility-disclosure"><summary>Data collected and safeguards</summary><div className="maintenance-details"><p className="meta"><strong>Collects: </strong>{details.collects}</p><p className="meta"><strong>Limits and recovery: </strong>{details.safeguards} Batches run serially, paced two seconds apart. Starting an operation locks other maintenance actions.</p></div></details></div>;
}
