import { useMemo, useState, type CSSProperties } from 'react';
import { Filter } from 'lucide-react';
import type { Catalog, Viewer } from '../shared/types';
import { calculateMetrics, matchesMetricsFilter, selectedAppearances, contributorMetrics, metricsDashboard, metricsScoreDimensions, type MetricsScoreDimension, type RankedAppearance, type MetricsFilter, type PopularAppearance } from '../shared/metrics';
import { dateLabel, Empty, MovieLink, Poster } from './components';
import { runtimeLabel } from './FilmIdentity';
import { formatScore100 } from './presentation';
import { ClubIdentity } from './ClubIdentity';

const score = (value: number | null) => value === null ? 'No scores yet' : `${value.toFixed(2)} / 10`;
const countLabel = (value: number) => value.toLocaleString('en-AU');
function DistributionRow({label,value,detail,width,colour}: {label: string; value: string; detail?: string; width: number; colour: string}) {
  return <div className="metrics-distribution-row" style={{'--chart-colour':`var(--${colour})`} as CSSProperties}><div className="metrics-distribution-label"><span>{label}</span><strong>{value}</strong></div><div className="metrics-distribution-track" aria-hidden="true"><span style={{width:`${Math.max(0,Math.min(100,width))}%`}} /></div>{detail && <p className="meta">{detail}</p>}</div>;
}
export function MetricsScreen({catalog}: {catalog: Catalog; viewer: Viewer | null; onUpdated: () => Promise<void>}) {
  const [filter,setFilter] = useState<MetricsFilter>({kind: 'all'});
  const [topDimension,setTopDimension] = useState<MetricsScoreDimension>('imdb');
  const [bottomDimension,setBottomDimension] = useState<MetricsScoreDimension>('imdb');
  const all = useMemo(() => selectedAppearances(catalog),[catalog]);
  const rows = useMemo(() => filter.kind === 'all' ? all : all.filter(row => matchesMetricsFilter(row.session,filter)),[all,filter]);
  const contributions = useMemo(() => contributorMetrics(catalog,all),[catalog,all]);
  const metrics = useMemo(() => calculateMetrics(catalog,filter,{top:topDimension,bottom:bottomDimension},rows),[catalog,filter,topDimension,bottomDimension,rows]);
  const dashboard = useMemo(() => metricsDashboard(rows,all),[rows,all]);
  const commonDecade = [...dashboard.decades].sort((a,b) => b.count-a.count)[0];
  const popularityList = (title: string,items: PopularAppearance[]) => <section className="stack"><h3>{title}</h3>{items.length ? <ol className="metrics-popularity-list">{items.map(row => <li key={row.movie.id}><MovieLink movie={row.movie} className="metrics-poster-film"><Poster movie={row.movie} /><div><span className="movie-title">{row.movie.title}</span><p className="meta">{row.movie.year ?? 'Year unknown'}</p><strong>{countLabel(row.votes)} IMDb votes</strong></div></MovieLink></li>)}</ol> : <p className="meta">No IMDb vote data for this selection.</p>}</section>;
  const list = (direction: 'Top' | 'Bottom',id: MetricsScoreDimension,setDimension: (id: MetricsScoreDimension) => void,rows: RankedAppearance[]) => {
    const dimension = metricsScoreDimensions.find(d => d.id === id)!;
    return <section className="stack"><h2>{direction} 5 by {dimension.name}</h2><div className="metrics-score-filters" role="group" aria-label={`${direction} 5 score filter`}>{metricsScoreDimensions.map(d => <button type="button" key={d.id} aria-label={d.name} aria-pressed={id === d.id} onClick={() => setDimension(d.id)}>{d.label}</button>)}</div>{!rows.length ? <p className="meta">No appearances with {dimension.name} scores yet.</p> : <ol className="metrics-list">{rows.map(row => {
    const host = catalog.members.find(m => m.id === row.session.host_member_id);
    const cycle = catalog.cycles.find(c => c.id === row.session.cycle_id);
    return <li key={`${row.session.id}:${row.position}`}><MovieLink movie={row.movie} className="metrics-film-item"><div className="stack"><span className="movie-title">{row.movie.title}</span>{row.movie.year ? <span className="meta">({row.movie.year})</span> : null}<p className="meta">{row.session.date_precision === 'exact' && !cycle?.import_source && !cycle?.import_key ? `${dateLabel(row.session.event_date)} · ` : ''}{cycle ? `Cycle ${cycle.ordinal} ` : ''}Film {row.position}</p></div><strong>{dimension.scale === 100 ? formatScore100(row.selectedScore) : dimension.scale === 10 ? row.selectedScore.toFixed(1) : String(Number(row.selectedScore.toFixed(2)))} / {dimension.scale}</strong>{row.session.kind === 'classics' ? <ClubIdentity identity={{kind: 'classics'}} /> : host ? <ClubIdentity identity={{kind: 'member',member: host}} /> : <span className="meta">Host unknown</span>}</MovieLink></li>;
  })}</ol>}</section>;
  };
  return <div className="stack metrics-content"><div className="metrics-filters" role="group" aria-label="Metrics identity filter"><button type="button" aria-pressed={filter.kind === 'all'} onClick={() => setFilter({kind: 'all'})}><Filter size={16} aria-hidden="true" />ALL</button>{catalog.members.filter(m => m.sort_order >= 1 && m.sort_order <= 4).sort((a,b) => a.sort_order-b.sort_order).map(member => <button type="button" key={member.id} aria-pressed={filter.kind === 'member' && filter.memberId === member.id} onClick={() => setFilter({kind: 'member',memberId: member.id})}><Filter size={12} className="metrics-filter-icon" aria-hidden="true" /><ClubIdentity identity={{kind: 'member',member}} /></button>)}<button type="button" aria-pressed={filter.kind === 'classics'} onClick={() => setFilter({kind: 'classics'})}><Filter size={12} className="metrics-filter-icon" aria-hidden="true" /><ClubIdentity identity={{kind: 'classics'}} /></button></div><p className="meta">All time · actual hosts · repeat screenings count.</p>
    <h2>Snapshot</h2><div className="metrics-summary">{[['Events',metrics.events],['Films brought',metrics.appearances],['Unique films',metrics.uniqueFilms],['Average IMDb',score(metrics.imdbAverage)]].map(([label,value]) => <div className="card stat" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>
    <p className="meta">{metrics.appearances ? `${metrics.imdbScored} / ${metrics.appearances} appearances have IMDb scores. ${metrics.genreCovered} / ${metrics.appearances} have recognised stored genres; ${metrics.uncategorised} are Uncategorised.` : 'No film appearances for this selection.'}</p>
    {!metrics.events && <Empty title="No events for this identity">Metrics will appear when qualifying events are recorded in History.</Empty>}
    <section className="stack metrics-section"><h2>Contribution by host</h2><p className="meta">All-time films brought · independent of the selected identity.</p><figure className="comparison-chart"><figcaption>Films brought</figcaption>{contributions.map((row,index) => <div className="chart-row" key={row.label}><span>{row.label}</span><span className="chart-track" aria-hidden="true"><span className={index % 2 === 0 ? 'chart-bar-jeans' : 'chart-bar-lavender'} style={{width:`${row.count/Math.max(1,...contributions.map(r => r.count))*100}%`}} /></span><strong>{row.count}</strong></div>)}</figure></section>
    <section className="stack metrics-section"><h2>Taste</h2><div className="metrics-taste-grid"><section className="stack metrics-fingerprint"><h3>Genre fingerprint</h3><p className="meta">{filter.kind === 'all' ? 'Each contributor’s signature against the whole club.' : 'Distinctive genres compared with the whole club.'}</p>{filter.kind === 'all' ? contributions.map(row => <div className="metrics-signature" key={row.label}><strong>{row.label}</strong>{row.signature ? <DistributionRow label={row.signature.genre} value={`${row.signature.ratio.toFixed(1)}x club`} detail={`${row.signature.count} appearances · ${row.signature.percentage.toFixed(1)}%`} width={row.signature.percentage} colour={row.signature.colour} /> : <span className="meta">No recognised genres</span>}</div>) : dashboard.fingerprint.length ? dashboard.fingerprint.map(g => <DistributionRow key={g.genre} label={g.genre} value={`${g.ratio.toFixed(1)}x club`} detail={`${g.count} appearances · ${g.percentage.toFixed(1)}%`} width={g.percentage} colour={g.colour} />) : <p className="meta">No recognised genres for this selection.</p>}</section>
    <section className="stack metrics-decades"><h3>Release decades</h3>{commonDecade && <p className="meta">Most common: {commonDecade.label} · {commonDecade.count} appearances</p>}{dashboard.decades.length ? dashboard.decades.map(d => <DistributionRow key={d.label} label={d.label} value={`${d.count} · ${d.percentage.toFixed(1)}%`} width={d.percentage} colour={d.colour} />) : <p className="meta">No film appearances yet.</p>}</section>
    <section className="stack metrics-directors"><h3>Top 5 Directors</h3><p className="meta">{rows.length ? `Director known for ${dashboard.directors.covered} / ${rows.length} appearances` : 'No film appearances yet.'}</p>{dashboard.directors.top.length ? dashboard.directors.top.map(d => <DistributionRow key={d.name} label={d.name} value={`${d.count} · ${d.percentage.toFixed(1)}%`} width={d.percentage} colour={d.colour} />) : <p className="meta">No director data for this selection.</p>}</section></div></section>
    <section className="stack metrics-section"><h2>Ratings</h2><section className="stack"><h3>Ratings Profile</h3><p className="meta">Mean /100 · genuine stored ratings · repeats count</p><div className="metrics-rating-profile">{dashboard.ratings.map(r => <div key={r.id} title={r.id === 'metacritic' ? 'Metacritic critic' : r.name} aria-label={r.id === 'metacritic' ? 'Metacritic critic' : r.name}><DistributionRow label={r.label} value={r.mean === null ? '—' : formatScore100(r.mean)} detail={r.mean === null ? rows.length ? `0 / ${rows.length} scored` : 'No scores' : `Median ${formatScore100(r.median!)} · ${r.coverage} / ${rows.length} scored`} width={r.mean ?? 0} colour={r.colour} /></div>)}</div></section><div className="metrics-rankings">{list('Top',topDimension,setTopDimension,metrics.top)}{list('Bottom',bottomDimension,setBottomDimension,metrics.bottom)}</div></section>
    <section className="stack metrics-section"><h2>Popularity &amp; Obscurity</h2><p className="meta">{dashboard.popularity.median === null ? 'No IMDb vote data for this selection.' : `Median ${countLabel(dashboard.popularity.median)} IMDb votes · ${dashboard.popularity.coverage} / ${rows.length} appearances`} · Lists show unique films.</p><div className="metrics-paired">{popularityList('Most popular',dashboard.popularity.popular)}{popularityList('Most obscure',dashboard.popularity.obscure)}</div></section>
    <section className="stack metrics-section"><h2>Extremes cabinet</h2><div className="metrics-extremes">{([
      {label:'Highest IMDb',row:dashboard.extremes.highest,value:dashboard.extremes.highest ? score(dashboard.extremes.highest.imdb) : null},
      {label:'Lowest IMDb',row:dashboard.extremes.lowest,value:dashboard.extremes.lowest ? score(dashboard.extremes.lowest.imdb) : null},
      {label:'Oldest',row:dashboard.extremes.oldest,value:dashboard.extremes.oldest?.movie.year},
      {label:'Longest',row:dashboard.extremes.longest,value:runtimeLabel(dashboard.extremes.longest?.movie.runtime ?? null)},
    ]).map(item => <section className="stack" key={item.label}><h3>{item.label}</h3>{item.row ? <MovieLink movie={item.row.movie} className="metrics-poster-film"><Poster movie={item.row.movie} large /><div><span className="movie-title">{item.row.movie.title}</span><p className="meta">{item.row.movie.year ?? 'Year unknown'}</p><strong>{item.value}</strong></div></MovieLink> : <p className="meta">No data for this selection.</p>}</section>)}</div></section>
    <section className="stack metrics-section"><h2>Genre detail</h2><p className="meta">An appearance counts once in each of its genres, so totals may exceed film appearances. Percentages use all selected appearances. Averages use only scored appearances.</p>{metrics.genres.length ? <table className="metrics-table"><thead><tr><th scope="col">Genre</th><th scope="col" aria-label="Appearance count">Count</th><th scope="col">Share</th><th scope="col">IMDb</th></tr></thead><tbody>{metrics.genres.map(g => <tr key={g.genre}><th scope="row">{g.genre}</th><td>{g.appearances}</td><td>{g.percentage.toFixed(1)}%</td><td>{g.imdbAverage === null ? 'No scores' : g.imdbAverage.toFixed(2)}<small>{g.imdbScored} / {g.appearances} scored</small></td></tr>)}</tbody></table> : <p className="meta">No film appearances yet.</p>}</section>

  </div>;
}
