import { useMemo, useState, useId, type CSSProperties } from 'react';
import { ComparisonBars, RatingCircles } from './MetricsVisuals';
import { Filter } from 'lucide-react';
import type { Catalog, Viewer } from '../shared/types';
import { metricsPalette, calculateMetrics, matchesMetricsFilter, selectedAppearances, contributorMetrics, metricsDashboard, metricsScoreDimensions, type MetricsScoreDimension, type RankedAppearance, type MetricsFilter, type PopularAppearance } from '../shared/metrics';
import { dateLabel, MovieLink, Poster } from './components';
import { runtimeLabel } from './FilmIdentity';
import { formatScore100 } from './presentation';
import { ClubIdentity } from './ClubIdentity';
import { EnrichedMetrics, CreatorExtremes, useMetricsEnrichment } from './EnrichedMetrics';
import { filmExtremes } from '../shared/metrics-enrichment';

import { metricsTabs, type MetricsTab } from './metrics-tabs';

function revealTab(button: HTMLButtonElement) {
  const strip = button.parentElement;
  if (!strip) return;
  const bounds = strip.getBoundingClientRect(), target = button.getBoundingClientRect();
  if (target.left < bounds.left) strip.scrollLeft += target.left-bounds.left;
  else if (target.right > bounds.right) strip.scrollLeft += target.right-bounds.right;
}
const decadeLabel = (label: string) => /^\d{4}s$/.test(label) ? `'${label.slice(2)}` : label;
const countLabel = (value: number) => value.toLocaleString('en-AU');
export function MetricsScreen({catalog}: {catalog: Catalog; viewer: Viewer | null; onUpdated: () => Promise<void>}) {
  const [category,setCategory] = useState<MetricsTab>('top-bottom');
  const tabId = useId();
  const [filter,setFilter] = useState<MetricsFilter>({kind: 'all'});
  const [topDimension,setTopDimension] = useState<MetricsScoreDimension>('imdb');
  const [bottomDimension,setBottomDimension] = useState<MetricsScoreDimension>('imdb');
  const all = useMemo(() => selectedAppearances(catalog),[catalog]);
  const rows = useMemo(() => filter.kind === 'all' ? all : all.filter(row => matchesMetricsFilter(row.session,filter)),[all,filter]);
  const contributions = useMemo(() => contributorMetrics(catalog,all),[catalog,all]);
  const metrics = useMemo(() => calculateMetrics(catalog,filter,{top:topDimension,bottom:bottomDimension},rows),[catalog,filter,topDimension,bottomDimension,rows]);
  const dashboard = useMemo(() => metricsDashboard(rows,all),[rows,all]);
  const enrichment = useMetricsEnrichment();
  const extremes = useMemo(() => filmExtremes(rows),[rows]);
  const commonDecade = [...dashboard.decades].sort((a,b) => b.count-a.count)[0];
  const popularityList = (title: string,items: PopularAppearance[]) => <section className="stack"><h3>{title}</h3>{items.length ? <ol className="metrics-popularity-list">{items.map(row => <li key={row.movie.id}><MovieLink movie={row.movie} className="metrics-poster-film"><Poster movie={row.movie} /><div><span className="movie-title">{row.movie.title}</span><p className="meta">{row.movie.year ?? 'Year unknown'}</p><strong>{countLabel(row.votes)} IMDb votes</strong></div></MovieLink></li>)}</ol> : <p className="meta">No IMDb vote data for this selection.</p>}</section>;
  const list = (direction: 'Top' | 'Bottom',id: MetricsScoreDimension,setDimension: (id: MetricsScoreDimension) => void,rows: RankedAppearance[]) => {
    const dimension = metricsScoreDimensions.find(d => d.id === id)!;
    return <section className="stack" data-metric={direction === 'Top' ? 'U' : 'V'}><h2>{direction} 5 by {dimension.name}</h2><div className="metrics-score-filters" role="group" aria-label={`${direction} 5 score filter`}>{metricsScoreDimensions.map(d => <button type="button" key={d.id} aria-label={d.name} aria-pressed={id === d.id} onClick={() => setDimension(d.id)}>{d.label}</button>)}</div>{!rows.length ? <p className="meta">No appearances with {dimension.name} scores yet.</p> : <ol className="metrics-list">{rows.map(row => {
    const host = catalog.members.find(m => m.id === row.session.host_member_id);
    const cycle = catalog.cycles.find(c => c.id === row.session.cycle_id);
    return <li key={`${row.session.id}:${row.position}`}><MovieLink movie={row.movie} className="metrics-film-item"><div className="stack"><span className="movie-title">{row.movie.title}</span>{row.movie.year ? <span className="meta">({row.movie.year})</span> : null}<p className="meta">{row.session.date_precision === 'exact' && !cycle?.import_source && !cycle?.import_key ? `${dateLabel(row.session.event_date)} · ` : ''}{cycle ? `Cycle ${cycle.ordinal} ` : ''}Film {row.position}</p></div><div className="metrics-film-footer"><strong>{dimension.scale === 100 ? formatScore100(row.selectedScore) : dimension.scale === 10 ? row.selectedScore.toFixed(1) : String(Number(row.selectedScore.toFixed(2)))} / {dimension.scale}</strong>{row.session.kind === 'classics' ? <ClubIdentity identity={{kind: 'classics'}} /> : host ? <ClubIdentity identity={{kind: 'member',member: host}} /> : <span className="meta">Host unknown</span>}</div></MovieLink></li>;
  })}</ol>}</section>;
  };
  return <div className="stack metrics-content"><div className="metrics-filters" role="group" aria-label="Metrics identity filter"><button type="button" aria-pressed={filter.kind === 'all'} onClick={() => setFilter({kind: 'all'})}><Filter size={16} aria-hidden="true" />ALL</button>{catalog.members.filter(m => m.sort_order >= 1 && m.sort_order <= 4).sort((a,b) => a.sort_order-b.sort_order).map(member => <button type="button" key={member.id} aria-pressed={filter.kind === 'member' && filter.memberId === member.id} onClick={() => setFilter({kind: 'member',memberId: member.id})}><Filter size={12} className="metrics-filter-icon" aria-hidden="true" /><ClubIdentity identity={{kind: 'member',member}} /></button>)}<button type="button" aria-pressed={filter.kind === 'classics'} onClick={() => setFilter({kind: 'classics'})}><Filter size={12} className="metrics-filter-icon" aria-hidden="true" /><ClubIdentity identity={{kind: 'classics'}} /></button></div><div className="metrics-category-tabs" role="tablist" aria-label="Metrics categories">{metricsTabs.map((tab,index) => <button type="button" key={tab.id} id={`${tabId}-tab-${tab.id}`} role="tab" aria-selected={category === tab.id} aria-controls={`${tabId}-panel`} tabIndex={category === tab.id ? 0 : -1} onClick={event => {setCategory(tab.id);revealTab(event.currentTarget);}} onKeyDown={event => {
      const next = event.key === 'ArrowRight' ? (index+1)%metricsTabs.length : event.key === 'ArrowLeft' ? (index+metricsTabs.length-1)%metricsTabs.length : event.key === 'Home' ? 0 : event.key === 'End' ? metricsTabs.length-1 : null;
      if (next === null) return;
      event.preventDefault(); setCategory(metricsTabs[next].id);
      const button = event.currentTarget.parentElement?.querySelectorAll<HTMLButtonElement>('[role="tab"]')[next];
      button?.focus({preventScroll:true});
      if (button) revealTab(button);
    }}>{tab.label}</button>)}</div><div className="stack metrics-panel" role="tabpanel" id={`${tabId}-panel`} aria-labelledby={`${tabId}-tab-${category}`} tabIndex={0}><p className="meta">All time · actual hosts · repeat screenings count.</p>
    {category === 'top-bottom' && <><div className="stack" data-metric="E"><section className="stack metrics-directors"><h3>Top Directors</h3><p className="meta">{rows.length ? `Director known for ${dashboard.directors.covered} / ${rows.length} appearances` : 'No film appearances yet.'}</p>{dashboard.directors.top.length ? dashboard.directors.top.map(d => <div className="metrics-distribution-label" key={d.name}><span>{d.name}</span><span className="meta">{d.count} appearances · {d.percentage.toFixed(1)}%</span></div>) : <p className="meta">No director data for this selection.</p>}</section></div><div className="metrics-rankings">{list('Top',topDimension,setTopDimension,metrics.top)}{list('Bottom',bottomDimension,setBottomDimension,metrics.bottom)}</div><div className="stack" data-metric="W"><section className="stack metrics-section"><h2>Popularity &amp; Obscurity</h2><p className="meta">{dashboard.popularity.median === null ? 'No IMDb vote data for this selection.' : `Median ${countLabel(dashboard.popularity.median)} IMDb votes · ${dashboard.popularity.coverage} / ${rows.length} appearances`} · Lists show unique films.</p><div className="metrics-paired">{popularityList('Most popular',dashboard.popularity.popular)}{popularityList('Most obscure',dashboard.popularity.obscure)}</div></section></div></>}
    {category === 'fingerprints' && <><div className="stack" data-metric="C"><section className="stack metrics-fingerprint"><h3>Genre fingerprint</h3><p className="meta">{filter.kind === 'all' ? 'Each contributor’s signature against the whole club.' : 'Distinctive genres compared with the whole club.'}</p>{filter.kind === 'all' ? contributions.map(row => <div className="metrics-signature" key={row.label}><strong>{row.label}</strong>{row.signature ? <ComparisonBars ratio={row.signature.ratio} label={row.signature.genre} value={`${row.signature.ratio.toFixed(1)}x club`} detail={`${row.signature.count} appearances · ${row.signature.percentage.toFixed(1)}%`} colour={row.signature.colour} /> : <span className="meta">No recognised genres</span>}</div>) : dashboard.fingerprint.length ? dashboard.fingerprint.map(g => <ComparisonBars ratio={g.ratio} key={g.genre} label={g.genre} value={`${g.ratio.toFixed(1)}x club`} detail={`${g.count} appearances · ${g.percentage.toFixed(1)}%`} colour={g.colour} />) : <p className="meta">No recognised genres for this selection.</p>}</section></div></>}
    {category === 'general' && <><div className="stack" data-metric="B"><section className="stack metrics-section"><h2>Contribution by host</h2><p className="meta">All-time films brought · independent of the selected identity.</p><figure className="comparison-chart"><figcaption>Films brought</figcaption>{contributions.map((row,index) => <div className="chart-row" key={row.label}><span>{row.label}</span><span className="chart-track" aria-hidden="true"><span className={index % 2 === 0 ? 'chart-bar-jeans' : 'chart-bar-lavender'} style={{width:`${row.count/Math.max(1,...contributions.map(r => r.count))*100}%`}} /></span><strong>{row.count}</strong></div>)}</figure></section></div><div className="stack" data-metric="D"><section className="stack metrics-decades"><h3>Release decades</h3>{commonDecade && <p className="meta">Most common: {decadeLabel(commonDecade.label)} · {commonDecade.percentage.toFixed(1)}%</p>}{dashboard.decades.length ? <><div className="metrics-stack-bar" aria-hidden="true">{dashboard.decades.map(d => <span key={d.label} style={{width:`${d.percentage}%`,background:`var(--${d.colour})`}} />)}</div><div className="metrics-stack-legend">{dashboard.decades.map(d => <span key={d.label}><i aria-hidden="true" style={{background:`var(--${d.colour})`}} />{decadeLabel(d.label)} · {d.percentage.toFixed(1)}%</span>)}</div></> : <p className="meta">No film appearances yet.</p>}</section></div><div className="stack" data-metric="Y"><section className="stack metrics-section"><h2>Genre detail</h2><p className="meta">An appearance counts once in each of its genres, so totals may exceed film appearances. Percentages use all selected appearances. Averages use only scored appearances.</p>{metrics.genres.length ? <div className="metrics-genre-scroll" tabIndex={0} role="region" aria-label="Genre detail"><table className="metrics-table"><thead><tr><th scope="col">Genre</th><th scope="col" aria-label="Appearance count">Count</th><th scope="col">Share</th><th scope="col">IMDb</th></tr></thead><tbody>{metrics.genres.map(g => <tr key={g.genre}><th scope="row">{g.genre}</th><td>{g.appearances}</td><td>{g.percentage.toFixed(1)}%</td><td>{g.imdbAverage === null ? 'No scores' : g.imdbAverage.toFixed(2)}</td></tr>)}</tbody></table></div> : <p className="meta">No film appearances yet.</p>}</section></div></>}
    {category === 'averages' && <><div className="stack" data-metric="T"><section className="stack"><h3>Ratings Profile</h3><p className="meta">Mean /100 · genuine stored ratings · repeats count</p><div className="metrics-rating-profile">{dashboard.ratings.map(r => <div key={r.id} title={r.id === 'metacritic' ? 'Metacritic critic' : r.name} aria-label={r.id === 'metacritic' ? 'Metacritic critic' : r.name}><div className="stack"><div className="metrics-distribution-label"><span>{r.label}</span><strong>Mean {r.mean === null ? '—' : `${formatScore100(r.mean)} / 100`}</strong></div><RatingCircles mean={r.mean ?? 0} colour={r.colour} /><p className="meta">{r.median === null ? 'No scores' : `Median ${formatScore100(r.median)}`}</p></div></div>)}</div></section></div></>}
    {category === 'extremes' && <><div className="stack" data-metric="X"><section className="stack metrics-section"><h2>Extremes cabinet</h2><div className="metrics-extremes">{([
      {label:'Top Critic',report:extremes.topCritic,value:extremes.topCritic ? `${extremes.topCritic.value.toFixed(1)} / 100` : 'No scores'},
{label:'Top Audience',report:extremes.topAudience,value:extremes.topAudience ? `${extremes.topAudience.value.toFixed(1)} / 100` : 'No scores'},
{label:'Bottom Critic',report:extremes.bottomCritic,value:extremes.bottomCritic ? `${extremes.bottomCritic.value.toFixed(1)} / 100` : 'No scores'},
{label:'Bottom Audience',report:extremes.bottomAudience,value:extremes.bottomAudience ? `${extremes.bottomAudience.value.toFixed(1)} / 100` : 'No scores'},
      {label:'Oldest',report:extremes.oldest,value:extremes.oldest?.value},
      {label:'Longest',report:extremes.longest,value:runtimeLabel(extremes.longest?.value ?? null)},
    ]).map((item,index) => <section className="stack metrics-film-extreme" key={item.label}><h3 style={{'--extreme-colour':`var(--${metricsPalette[index]})`} as CSSProperties}>{item.label}</h3>{item.report ? <><strong>{item.report.items.length > 1 ? `${item.report.items.length}-way tie · ` : ''}{item.value}</strong>{item.report.items.map(row => <MovieLink key={row.movie.id} movie={row.movie} className="metrics-poster-film"><Poster movie={row.movie} large /><div><span className="movie-title">{row.movie.title}</span><p className="meta">{row.movie.year ?? 'Year unknown'}</p></div></MovieLink>)}</> : <p className="meta">No data for this selection.</p>}</section>)}<CreatorExtremes rows={rows} data={enrichment.data} /></div></section></div></>}
    <EnrichedMetrics category={category} catalog={catalog} all={all} rows={rows} filter={filter} {...enrichment} />
    </div>
  </div>;
}
