import { useRef, useState } from 'react';
import { CalendarPlus, ListChecks, ListPlus, Save, Settings } from 'lucide-react';
import type { Catalog, Rotation, Viewer } from '../shared/types';
import { api } from './api';
import { Action, RouteLink } from './components';
import { ClubIdentity } from './ClubIdentity';
import { BuilderSetPicker } from './BuilderSetPicker';
export function RotationCard({catalog,rotation,viewer,onUpdated,onUseBuilder}: {catalog: Catalog; rotation: Rotation | null; viewer: Viewer | null; onUpdated: () => void; onUseBuilder: (movieIds: string[]) => void}) {
  const nominal = catalog.members.find(m => m.sort_order === rotation?.nominal_slot);
  const personal = rotation?.nominal_slot !== 5 && nominal && viewer?.id === nominal.id;
  const [choosing,setChoosing] = useState(false);
  const pickerTrigger = useRef<HTMLButtonElement | null>(null);
  const closePicker = () => { setChoosing(false); pickerTrigger.current?.focus(); };
  const [editing,setEditing] = useState(false), [slot,setSlot] = useState(rotation?.nominal_slot ?? 1), [cycleId,setCycleId] = useState(rotation?.cycle_id ?? ''), [reason,setReason] = useState(''), [error,setError] = useState(''), [busy,setBusy] = useState(false);
  return <div className={`turn-card-area ${personal ? 'turn-card-area-personal' : ''}`}><section className={`card stack turn-card ${personal ? 'turn-card-personal' : ''}`}><h2>{personal ? 'It is your turn' : 'Current turn'}</h2>{rotation ? <div className="turn-row"><div className="turn-identity">{rotation.nominal_slot === 5 ? <ClubIdentity identity={{kind: 'classics'}} /> : nominal ? <ClubIdentity identity={{kind: 'member',member: nominal}} /> : <p>Nominal member position {rotation.nominal_slot} is unprovisioned.</p>}</div><div className="button-set turn-actions">{personal && <><RouteLink to="builder" icon={ListPlus} variant="primary">Plan in Builder</RouteLink><Action icon={ListChecks} onClick={e => { pickerTrigger.current = e.currentTarget; setChoosing(true); }}>Use from Builder</Action></>}{rotation.nominal_slot === 5 && <RouteLink to="classics" icon={ListPlus} variant="secondary">View Watch Order</RouteLink>}<RouteLink to="event" icon={CalendarPlus} variant={rotation.nominal_slot === 5 ? 'primary' : 'tertiary'}>Record an event</RouteLink></div></div> : <p className="meta">Current turn has not been initialised. An administrator can set it after historical review.</p>}
    {viewer?.role === 'admin' && <details className="utility-disclosure"><summary>Admin · rotation correction</summary><div className="stack"><Action icon={Settings} variant="tertiary" onClick={() => { setSlot(rotation?.nominal_slot ?? 1); setCycleId(rotation?.cycle_id ?? ''); setEditing(!editing); }}>Correct current turn</Action>{editing && <form className="stack" onSubmit={e => { e.preventDefault(); setBusy(true); setError(''); void api.correctRotation({cycle_id: slot === 1 ? null : cycleId || null,nominal_slot: slot,version: rotation?.version ?? null,reason}).then(() => { setEditing(false); onUpdated(); }).catch(e => setError(e instanceof Error ? e.message : 'Correction failed.')).finally(() => setBusy(false)); }}><p className="notice">This changes explicit rotation only. Review History and explain the correction.</p><label className="input-label">Nominal slot<select className="field__input" value={slot} onChange={e => setSlot(Number(e.target.value))}>{[1,2,3,4,5].map(n => <option value={n} key={n}>{n} · {n === 5 ? 'CLSC' : catalog.members.find(m => m.sort_order === n)?.display_name.toUpperCase()}</option>)}</select></label>{slot !== 1 && <label className="input-label">Cycle<select required className="field__input" value={cycleId} onChange={e => setCycleId(e.target.value)}><option value="">Choose a reviewed cycle</option>{catalog.cycles.map(c => <option value={c.id} key={c.id}>{c.title || `Cycle ${c.ordinal}`} · {c.rough_date}</option>)}</select></label>}<label className="input-label">Reason<textarea required className="field__input" maxLength={2000} value={reason} onChange={e => setReason(e.target.value)} /></label><Action icon={Save} type="submit" variant="primary" disabled={busy}>Save correction</Action>{error && <p className="error-message" role="alert">{error}</p>}</form>}</div></details>}
  </section>{choosing && personal && viewer && <BuilderSetPicker catalog={catalog} viewer={viewer} onClose={closePicker} onChoose={movieIds => { closePicker(); onUseBuilder(movieIds); }} />}</div>;
}
