import type { Catalog } from '../../../shared/types';
import type { Appearance, MetricsFilter } from '../../../shared/metrics';
import type { MetricsEnrichment } from '../../../shared/metrics-enrichment';
import { sharedStars, partnerships, genreRevenue, expensiveFlops, classificationAcclaim, platforms, collectionCompletion, awardsReport } from '../../../shared/metrics-staging/films';
import { useStagingReports } from './cache';
import { MetricsResults } from '../../MetricsResults';
import { MovieLink } from '../../components';
import { formatCount } from '../../../shared/format';
import { Report, Empty, Contributor, PairedBars, number, money } from './primitives';

export function PeopleReports({catalog,all,rows,filter,data,reportCache}:EvidenceProps) {
  const cached=useStagingReports([catalog,all,rows,filter,data],reportCache,'people');
  const stars=cached('stars',()=>sharedStars(catalog,all,data)),pairs=cached('pairs',()=>partnerships(rows,data));
  return <><Report title="Shared stars" note="Actors shared across the boobs.">{stars.length?<div className="staging-table-scroll" tabIndex={0} role="region" aria-label="Shared stars table"><table className="staging-stars-table"><caption className="visually-hidden">Actor appearances across Sean, Troy, Matt and Jess, and their total</caption><thead><tr><th scope="col">Actor</th>{catalog.members.filter(m=>m.sort_order>=1&&m.sort_order<=4).sort((a,b)=>a.sort_order-b.sort_order).map(m=><th scope="col" key={m.id}>{m.display_name}</th>)}<th scope="col">Total</th></tr></thead><tbody><MetricsResults label="Shared stars" tableColumns={6} items={stars} render={v=><tr key={v.id}><th scope="row">{v.label}</th>{v.counts.map((n,i)=><td key={i}>{formatCount(n)}</td>)}<td>{formatCount(v.appearances)}</td></tr>}/></tbody></table></div>:<Empty/>}</Report>
  <Report title="Creative partnerships" note="Most frequent director collaborations, with fifth-place ties.">{pairs.map(group=><section className="stack" key={group.role}><h3>Director + {group.role}</h3>{group.values.length?<MetricsResults label={`Director + ${group.role}`} items={group.values} render={v=><article className="staging-data-row" key={v.id}><strong>{v.director} + {v.partner}</strong><p className="meta">{formatCount(v.films.length)} distinct films</p><ul className="metrics-metadata-films">{v.films.map(row=><li key={row.movie.id}><MovieLink movie={row.movie}>{row.movie.title}</MovieLink></li>)}</ul></article>}/>:<Empty/>}</section>)}</Report></>;
}
export interface EvidenceProps {catalog:Catalog;all:Appearance[];rows:Appearance[];filter:MetricsFilter;data:MetricsEnrichment;reportCache?:Map<string,unknown>}
export function ReceptionReports(props:EvidenceProps) {
  const {catalog,all,rows,filter,data,reportCache}=props,cached=useStagingReports([catalog,all,rows,filter,data],reportCache,'reception');
  const revenue=cached('revenue',()=>genreRevenue(rows,data)),flops=cached('flops',()=>expensiveFlops(catalog,all,filter,data)),classification=cached('classification',()=>classificationAcclaim(rows,data)),offers=cached('offers',()=>platforms(rows));
  return <><Report title="Highest-grossing film by genre" note="The biggest reported worldwide gross in each genre.">{revenue.length?<table className="staging-revenue-table"><thead><tr><th scope="col">Genre</th><th scope="col">Film / reported gross</th></tr></thead><tbody>{revenue.map(v=><tr key={v.genre}><th scope="row">{v.genre}</th><td>{v.films.map(row=><div className="staging-gross-film" key={row.movie.id}><MovieLink movie={row.movie}><span className="movie-title">{row.movie.title}</span></MovieLink><p className="meta">{money(v.revenue)}</p></div>)}</td></tr>)}</tbody></table>:<Empty/>}</Report>
  <Report title="Expensive flops" note="The largest reported budget per reception point for each contributor.">{flops.map(group=><div className="staging-flop-group" key={group.label}>{group.values.length?group.values.map(v=><article className="staging-data-row staging-flop" key={v.row.movie.id}><Contributor catalog={catalog} filter={group.filter}/><div className="staging-flop-content"><MovieLink movie={v.row.movie}><span className="movie-title">{v.row.movie.title}</span></MovieLink><p className="meta">Budget: {money(v.budget)}</p><p className="meta">Score: {number(v.score)} / 100</p><p className="meta">Dollars per point: {money(v.ratio)}</p></div></article>):<div className="staging-data-row staging-flop"><Contributor catalog={catalog} filter={group.filter}/><Empty/></div>}</div>)}</Report>
  <Report title="Classification versus acclaim" note="Average critic and audience scores by Australian classification.">{classification.map(v=><article className="staging-data-row staging-classification" key={v.id}><h3>{v.label}</h3><PairedBars {...v}/></article>)}</Report>
  <Report title="Streaming platform representation" note="Top streaming services across selected films, from cached Australian availability.">{offers.values.length?<MetricsResults label="Streaming platforms" items={offers.values} render={v=><article className="staging-data-row" key={v.id}><strong>{v.name}</strong><p>Stream {formatCount(v.count)} distinct films · {number(v.percentage)}%</p><p className="meta">Rent {formatCount(v.access.find(a=>a.type==='rent')?.count ?? 0)} · Buy {formatCount(v.access.find(a=>a.type==='buy')?.count ?? 0)}</p></article>}/>:<Empty/>}<p className="meta">Australian watch availability: <a href="https://www.justwatch.com/au" target="_blank" rel="noreferrer">JustWatch</a> via <a href="https://www.themoviedb.org/" target="_blank" rel="noreferrer">TMDB</a>; cached options may change.</p></Report></>;
}
export function DiscoveryReports({catalog,all,rows,data,reportCache}:EvidenceProps) {
  const cached=useStagingReports([catalog,all,rows,data],reportCache,'discovery'),collections=cached('collections',()=>collectionCompletion(all,data)),awards=cached('awards',()=>awardsReport(rows,data));
  return <>{(['completed','unrequited'] as const).map(status=><Report key={status} title={status==='completed'?'Franchise / collection completed':'Unrequited collections'} note={status==='completed'?'Every TMDB collection film brought, as of the cached membership check.':'Collections with films still to bring, as of the cached membership check.'}>
    {collections[status].length?<MetricsResults label={status==='completed'?'Completed collections':'Unrequited collections'} items={collections[status]} render={v=><article className="staging-data-row" key={v.id}><h3>{v.name}</h3><p className="meta">{formatCount(v.films.length)} of {formatCount(v.total)} films</p><ul className="metrics-metadata-films">{v.films.map(row=><li key={row.movie.id}><MovieLink movie={row.movie}>{row.movie.title}</MovieLink></li>)}</ul>{v.missing.some(part=>part.title)&&<div className="staging-missing-films meta"><span>Not brought:</span>{v.missing.filter(part=>part.title).map(part=><span key={part.id}>{part.title}</span>)}</div>}</article>}/>:<Empty/>}
    {collections.pending>0&&<p className="meta">{formatCount(collections.pending)} eligible {collections.pending===1?'collection awaits':'collections await'} a validated membership check in Admin.</p>}
  </Report>)}
  <Report title="Awards and nominations" note="Reported wins and nominations, with the original awards wording."><p className="meta">{formatCount(awards.checked)} of {formatCount(awards.total)} distinct films checked · {formatCount(awards.values.length)} quantified · {formatCount(awards.unquantified)} unquantified · {formatCount(awards.unavailable)} unavailable.</p>{awards.values.length?<div className="staging-awards-table" role="table" aria-label="Reliably quantified OMDb awards"><div className="staging-awards-header" role="row"><span role="columnheader">Film / OMDb wording</span><span role="columnheader">Wins</span><span role="columnheader">Nominations</span></div><MetricsResults label="Awards" items={awards.values} render={v=><article className="staging-awards-row" role="row" key={v.row.movie.id}><div role="cell"><MovieLink movie={v.row.movie}>{v.row.movie.title}</MovieLink><p className="meta">{v.awards_text}</p><p className="meta">Critics {number(v.critic)} · Audiences {number(v.audience)}</p></div><div role="cell" aria-label={`Wins: ${v.wins===null?'unavailable':v.wins}`}><span className="staging-mobile-label">Wins: </span>{v.wins===null?'Unavailable':formatCount(v.wins)}</div><div role="cell" aria-label={`Nominations: ${v.nominations===null?'unavailable':v.nominations}`}><span className="staging-mobile-label">Nominations: </span>{v.nominations===null?'Unavailable':formatCount(v.nominations)}</div></article>}/></div>:<Empty/>}</Report></>;
}
