import type { Catalog } from '../../../shared/types';
import type { Appearance, MetricsFilter } from '../../../shared/metrics';
import type { MetricsEnrichment } from '../../../shared/metrics-enrichment';
import { sharedStars, partnerships, genreRevenue, expensiveFlops, classificationAcclaim, platforms, discoveries, collectionSpotlight, awardsReport } from '../../../shared/metrics-staging/films';
import { useStagingReports } from './cache';
import { MetricsResults } from '../../MetricsResults';
import { MovieLink } from '../../components';
import { formatCount } from '../../../shared/format';
import { Report, Empty, Contributor, FilmList, FilmContributors, PairedBars, number, money } from './primitives';

export function PeopleReports({catalog,all,rows,filter,data,reportCache}:EvidenceProps) {
  const cached=useStagingReports([catalog,all,rows,filter,data],reportCache,'people');
  const stars=cached('stars',()=>sharedStars(catalog,all,data,filter)),pairs=cached('pairs',()=>partnerships(rows,data));
  return <><Report title="Shared stars" note="Cast represented across at least three contributor identities. All-four-human overlap ranks first, then four identities, then three. Counts appearances and distinct films separately; cached cast is limited to the first 15 billed people. Filtering retains overlaps involving the selected contributor.">{stars.length?<MetricsResults label="Shared stars" items={stars} render={v=><article className="staging-data-row" key={v.id}><strong>{v.label}</strong><p>{formatCount(v.contributors.length)} contributors · {formatCount(v.appearances)} appearances · {formatCount(v.films.length)} distinct films</p><span className="staging-identities">{v.contributors.map(s=><Contributor key={s.label} catalog={catalog} filter={s.filter}/>)}</span><details><summary>Films establishing overlap</summary><FilmList films={v.films}/></details></article>}/>:<Empty/>}</Report>
  <Report title="Creative partnerships" note="Co-credits on distinct selected films. Writer includes deduplicated Writer/Screenplay credits. Canonical name-only director credits stay intact; identical names cannot establish distinct person identities.">{pairs.map(group=><section className="stack" key={group.role}><h3>Director + {group.role}</h3>{group.values.length?<MetricsResults label={`Director + ${group.role}`} items={group.values} render={v=><article className="staging-data-row" key={v.id}><strong>{v.director} + {v.partner}</strong><p>{formatCount(v.films.length)} distinct films</p><FilmList films={v.films}/></article>}/>:<Empty/>}</section>)}</Report></>;
}
export interface EvidenceProps {catalog:Catalog;all:Appearance[];rows:Appearance[];filter:MetricsFilter;data:MetricsEnrichment;reportCache?:Map<string,unknown>}
export function ReceptionReports(props:EvidenceProps) {
  const {catalog,all,rows,filter,data,reportCache}=props,cached=useStagingReports([catalog,all,rows,filter,data],reportCache,'reception');
  const revenue=cached('revenue',()=>genreRevenue(rows,data)),flops=cached('flops',()=>expensiveFlops(catalog,all,filter,data)),classification=cached('classification',()=>classificationAcclaim(rows,data)),offers=cached('offers',()=>platforms(rows));
  return <><Report title="Highest-grossing film by genre" note="Highest positive reported worldwide revenue in USD, retaining tied films. A multi-genre film can win several categories; amounts are not summed, profit or inflation-adjusted.">{revenue.length?revenue.map(v=><article className="staging-data-row" key={v.genre}><h3>{v.genre} · {money(v.revenue)}</h3><FilmList films={v.films}/></article>):<Empty/>}</Report>
  <Report title="Expensive flops" note="Reported USD budget ÷ combined score points; combined score is the arithmetic mean of critic and audience composites. Higher means more budget per reception point. This does not establish financial loss. One extreme per contributor, including true ties; distinct films.">{flops.map(group=><article className="staging-data-row" key={group.label}><Contributor catalog={catalog} filter={group.filter}/>{group.values.length?group.values.map(v=><p key={v.row.movie.id}><MovieLink movie={v.row.movie}>{v.row.movie.title}</MovieLink> · {money(v.budget)} budget · {number(v.score)} / 100 · {money(v.ratio)} per point</p>):<Empty/>}</article>)}</Report>
  <Report title="Classification versus acclaim" note="Australian classification resolved from cached release evidence. Means count available scored appearances separately; missing scores are excluded. Both bars use 0–100.">{classification.map(v=><article className="staging-data-row" key={v.id}><h3>{v.label}</h3><PairedBars {...v}/></article>)}</Report>
  <Report title="Streaming platform representation" note={`Cached Australian availability, not live availability. Counts distinct films per service and access type, across ${formatCount(offers.population)} selected distinct films. Films can appear on several services; percentages need not sum to 100%.`}>{offers.values.length?<MetricsResults label="Streaming platforms" items={offers.values} render={v=><article className="staging-data-row" key={v.id}><strong>{v.name}</strong><p>{formatCount(v.count)} distinct films · {number(v.percentage)}%</p><p className="meta">{v.access.map(a=>`${a.type==='subscription'?'Subscription':a.type.charAt(0).toUpperCase()+a.type.slice(1)} ${formatCount(a.count)}`).join(' · ')}</p></article>}/>:<Empty/>}<p className="meta">Australian watch availability: <a href="https://www.justwatch.com/au" target="_blank" rel="noreferrer">JustWatch</a> via <a href="https://www.themoviedb.org/" target="_blank" rel="noreferrer">TMDB</a>; cached options may change.</p></Report></>;
}
export function DiscoveryReports({catalog,all,rows,data,reportCache}:EvidenceProps) {
  const cached=useStagingReports([catalog,all,rows,data],reportCache,'discovery'),ranks=cached('discoveries',()=>discoveries(rows)),collections=cached('collections',()=>collectionSpotlight(rows,data)),awards=cached('awards',()=>awardsReport(rows,data));
  return <><Report title="Top 5 hidden gems" note={`At least 100 pooled votes on supported audience observations. Ranking = high audience-score midrank percentile × low-vote midrank percentile × 100 among ${formatCount(ranks.eligible)} eligible distinct films. Ties share percentiles; includes fifth-place ranking ties. Votes may overlap across sources, not unique people.`}>{ranks.hidden.length?<ol className="staging-ranking"><MetricsResults label="Hidden gems" list items={ranks.hidden} render={(v,i)=><li key={v.row.movie.id}><span>{formatCount(i+1)}. <MovieLink movie={v.row.movie}>{v.row.movie.title}</MovieLink><span className="meta">Audience {number(v.audience)} / 100 · {formatCount(v.votes)} pooled votes</span></span><strong>{number(v.rank)} index</strong></li>}/></ol>:<Empty/>}</Report>
  <Report title="Top 5 most cult" note="Audience-driven reception: at least 100 pooled audience votes and an audience composite at least 10 points above critics. Ranked by positive audience-minus-critic gap, with fifth-place ties; distinct films. This is an exploratory definition, not a claim of established cult status.">{ranks.cult.length?<ol className="staging-ranking"><MetricsResults label="Most cult" list items={ranks.cult} render={(v,i)=><li key={v.row.movie.id}><span>{formatCount(i+1)}. <MovieLink movie={v.row.movie}>{v.row.movie.title}</MovieLink><span className="meta">Critics {number(v.critic)} · Audiences {number(v.audience)} / 100 · {formatCount(v.votes)} pooled votes</span></span><strong>+{number(v.gap)} points</strong></li>}/></ol>:<Empty/>}</Report>
  <Report title="Franchise / collection spotlight" note="TMDB groupings do not establish precise franchise continuity or instalment order. Counts distinct selected films. Successfully checked standalone films are known negatives; unchecked or inconclusive films remain unknown."><p>{formatCount(collections.members)} collection films among {formatCount(collections.total)} selected films · {collections.total?number(collections.members/collections.total*100):'Unavailable'}% of selected films have confirmed membership.</p><p className="meta">{formatCount(collections.checked)} conclusively checked · {formatCount(collections.standalone)} confirmed without a collection · {formatCount(collections.total-collections.checked)} unknown. Membership among checked films: {collections.percentage===null?'Unavailable':`${number(collections.percentage)}%`}.</p>{collections.values.length?<MetricsResults label="Collections" items={collections.values} render={v=><article className="staging-data-row" key={v.id}><h3>{v.name}</h3><p>{formatCount(v.films.length)} distinct films</p><FilmContributors catalog={catalog} films={v.films} all={all}/><FilmList films={v.films}/></article>}/>:<Empty/>}</Report>
  <Report title="Awards and nominations" note="Reliably parsed OMDb aggregate counts, including known zero. Unknown counts remain unavailable; named prizes are not added to aggregate totals. Original wording is retained. Ranked by known wins, then known nominations; incomplete coverage is explicit."><p className="meta">{formatCount(awards.checked)} of {formatCount(awards.total)} distinct films checked · {formatCount(awards.values.length)} quantified · {formatCount(awards.unquantified)} unquantified · {formatCount(awards.unavailable)} unavailable.</p>{awards.values.length?<div className="staging-awards-table" role="table" aria-label="Reliably quantified OMDb awards"><div className="staging-awards-header" role="row"><span role="columnheader">Film / OMDb wording</span><span role="columnheader">Wins</span><span role="columnheader">Nominations</span></div><MetricsResults label="Awards" items={awards.values} render={v=><article className="staging-awards-row" role="row" key={v.row.movie.id}><div role="cell"><MovieLink movie={v.row.movie}>{v.row.movie.title}</MovieLink><p className="meta">{v.awards_text}</p><p className="meta">Critics {number(v.critic)} · Audiences {number(v.audience)}</p></div><div role="cell" aria-label={`Wins: ${v.wins===null?'unavailable':v.wins}`}><span className="staging-mobile-label">Wins: </span>{v.wins===null?'Unavailable':formatCount(v.wins)}</div><div role="cell" aria-label={`Nominations: ${v.nominations===null?'unavailable':v.nominations}`}><span className="staging-mobile-label">Nominations: </span>{v.nominations===null?'Unavailable':formatCount(v.nominations)}</div></article>}/></div>:<Empty/>}</Report></>;
}
