// Local rendered style contract. All API functions are synthetic and every external request is blocked.
import fs from 'node:fs';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.BOOKCLUB_PLAYWRIGHT_MODULE || '../.verification/node_modules/playwright/index.mjs');
const phase=process.env.BOOKCLUB_STYLE_PHASE || 'after';
const output='.verification/admin-final/rendered/'+phase;
fs.mkdirSync(output,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.BOOKCLUB_BROWSER_PATH || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
const page=await browser.newPage(),errors=[],blocked=[],samples=[];
page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',r=>{const u=new URL(r.request().url());if(['localhost','127.0.0.1'].includes(u.hostname))return r.fallback();blocked.push(u.hostname);return r.abort();});
await page.route('**/api/**',r=>{errors.push('Unmocked API request');return r.abort();});await page.route('**/__dev/**',r=>r.abort());
await page.route(/\/frontend\/api\.ts(?:\?.*)?$/,r=>r.fulfill({contentType:'text/javascript',body:"export const api=globalThis.__auditApi ??= {};export class ApiClientError extends Error {}export const hasSession=()=>true;export const setUnauthorizedHandler=()=>{};export const setDevMember=()=>{};export const clearSession=()=>{};export const storeSession=()=>{};"}));
const source=await(await fetch('http://localhost:4173/frontend/main.tsx')).text(),reactUrl=source.match(/from "([^"\n]+\/react\.js[^"\n]*)"/)[1],domUrl=source.match(/from "([^"\n]+\/react-dom_client\.js[^"\n]*)"/)[1];
await page.route(/\/frontend\/main\.tsx(?:\?.*)?$/,r=>r.fulfill({contentType:'text/javascript',body:`
import React from '${reactUrl}';import ReactDOM from '${domUrl}';import '/style.css';import '/frontend/app.css';
import '/node_modules/@fontsource/lexend-deca/300.css';import '/node_modules/@fontsource/lexend-deca/400.css';import '/node_modules/@fontsource/lexend-deca/500.css';import '/node_modules/@fontsource/lexend-deca/600.css';import '/node_modules/@fontsource/lexend-deca/700.css';import '/node_modules/@fontsource/lexend-deca/800.css';
import {App} from '/frontend/App.tsx';import {SignInScreen} from '/frontend/SignInScreen.tsx';import {AvatarScreen} from '/frontend/AvatarScreen.tsx';import {metricsFixture} from '/tests/metrics-fixture.ts';import {api} from '/frontend/api.ts';import {rankMovie} from '/shared/ranking.ts';import {metricsEnrichmentFixture} from '/tests/metrics-enrichment-fixture.ts';import {HistoryEvidence} from '/frontend/HistoryEvidence.tsx';import {LoadingView,Failure,Action,SourceScores} from '/frontend/components.tsx';import {EnrichedMetrics} from '/frontend/EnrichedMetrics.tsx';import {metricsDashboard,calculateMetrics} from '/shared/metrics.ts';
const catalog=metricsFixture();catalog.members.forEach((m,i)=>m.avatar=i+1);catalog.cycles=[{id:'cycle1',ordinal:1,rough_date:'2026-01-01',title:null}];catalog.sessions.forEach((s,i)=>{s.cycle_id='cycle1';s.cycle_slot=i%5+1;});
const candidates=[0,1,2].map(i=>({...catalog.movies[i],id:'candidate'+i,title:i===0?'A very long candidate title that tests wrapping beside row controls and narrow score presentations':'Candidate '+i,overview:'Synthetic overview with enough words to check the collapsed description. '.repeat(12),classic:true,seen:i===1?[]:catalog.members.map(m=>({member_id:m.id,seen:i===2?1:0,updated_at:''})),external_ids:[{provider:'tmdb',external_id:String(i+100)},{provider:'imdb',external_id:'tt000000'+i}],ranking:null,appearances:[]}));candidates[0].scores=[['imdb','rating'],['letterboxd','rating'],['metacritic','critic'],['metacritic','user'],['rottentomatoes','audience'],['rottentomatoes','critic'],['tmdb','rating'],['trakt','rating'],['rogerebert','rating']].map(([provider,metric])=>({provider,metric,raw_value:80,raw_scale:100,normalized_value:80,vote_count:123456,fetched_at:'2026-01-01'}));candidates.forEach(m=>m.ranking=rankMovie(m.scores,m.seen,catalog.members));catalog.movies.push(...candidates);window.auditCatalog=catalog;
api.health=async()=>({status:'ok',environment:'local',authenticationRequired:false,demo:true});api.me=async()=>({viewer:{...catalog.members[1],role:'admin'}});api.catalog=async()=>catalog;api.rotation=async()=>({id:1,cycle_id:null,nominal_slot:1,version:0,updated_at:''});api.builders=async()=>[{id:'set1',owner_member_id:'m2',title:'Synthetic private set',notes:'Synthetic saved notes',movie_ids:['a','b'],created_at:'2026-01-01',updated_at:'2026-01-01',revision:1}];
api.detail=async id=>({...catalog.movies.find(m=>m.id===id),appearances:[]});api.preview=async id=>({...catalog.movies[0],id,tmdb_id:Number(id)});api.search=async()=>({local:catalog.movies.map(m=>({...m,tmdbId:null,poster:null})),external:[],lookup:{available:true,message:null}});api.historyAudit=async()=>[];api.scoreMaintenanceStatus=async()=>({candidateIds:candidates.map(m=>m.id),eligibleDimensions:12345,unavailableDimensions:2345,unavailableFilms:1234});api.metricsEnrichment=async()=>metricsEnrichmentFixture();api.avatars=async()=>[1,2,3,4];
api.saveBuilder=async(body,id)=>({...body,id:id||'synthetic-set',owner_member_id:'m2',created_at:'2026-01-01',updated_at:'2026-01-01',revision:2});
api.maintainMovies=async(mode,ids)=>new Promise(resolve=>{window.finishBatch=(failed=false)=>{window.finishBatch=null;resolve({results:ids.map(id=>({movie:{...catalog.movies.find(m=>m.id===id),appearances:[]},providers:[{provider:'omdb',status:failed?'failed':'success',count:failed?0:1,blocking:failed,message:failed?'Synthetic blocking cooldown':'Saved',...(failed?{retryAfter:60}:{})}]}))});};});
api.enrichMetadataSelected=async ids=>new Promise(resolve=>{window.finishBatch=(failed=false)=>{window.finishBatch=null;resolve({results:ids.map(movieId=>({movieId,provider:'tmdb',status:failed?'failed':'success',message:failed?'Synthetic failed update':'Saved'}))});};});
api.enrichProvider=async(provider,ids)=>new Promise(resolve=>{window.finishBatch=(failed=false)=>{window.finishBatch=null;resolve({results:ids.map(movieId=>({movieId,status:failed?'failed':'updated',blocking:failed,message:failed?'Synthetic provider cooldown':'Saved',...(failed?{retryAfter:60}:{})})),canonicalChanged:false,stopped:failed});};});
const mode=new URL(location.href).searchParams.get('audit');if(mode==='counts'){for(let i=0;i<1234;i++){const movie={...candidates[0],id:'count'+i,scores:[],seen:[]};movie.ranking=rankMovie(movie.scores,movie.seen,catalog.members);catalog.movies.push(movie);}}if(mode==='operations'){for(let i=0;i<24;i++)catalog.movies.push({...candidates[0],id:'operation'+i});api.scoreMaintenanceStatus=async()=>({candidateIds:catalog.movies.map(m=>m.id),eligibleDimensions:12345,unavailableDimensions:2345,unavailableFilms:1234});}const node=mode==='loading'?React.createElement(LoadingView):mode==='failure'?React.createElement(Failure,{message:'Synthetic recoverable failure',retry:()=>{}}):mode==='evidence'?React.createElement(HistoryEvidence,{catalog,json:JSON.stringify({before:{event_date:'2026-01-01',movie_ids:['a','b'],kind:'hosted',host_member_id:'m2'},after:{event_date:'2026-01-02',movie_ids:['a'],kind:'classics'},turn_before:{nominal_slot:2,cycle_id:'cycle1'}})}):mode==='metrics-error'?React.createElement(EnrichedMetrics,{category:'fingerprints',dashboard:metricsDashboard([],[]),metrics:calculateMetrics(catalog),contributions:[],catalog,all:[],rows:[],filter:{kind:'all'},data:{movies:{}},status:'error',retry:()=>{}}):mode==='signin'?React.createElement(SignInScreen,{configured:false,error:'Synthetic sign-in error',busy:false,onCredential:async()=>{},onRetry:()=>{},onLocalLogin:async()=>{}}):mode==='avatar'?React.createElement(AvatarScreen,{viewer:catalog.members[1],onClaimed:()=>{},onLogout:()=>{},externalError:'Synthetic claim collision'}):React.createElement(App);ReactDOM.createRoot(document.getElementById('root')).render(node);
`}));

const sharp=(await import('sharp')).default;
const progressSample=async p=>{
 await p.evaluate(e=>e.scrollIntoView({block:'center'}));await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
 const values=await p.evaluate(e=>{const s=getComputedStyle(e);const color=token=>{const probe=document.createElement('span');probe.style.color='var('+token+')';document.body.appendChild(probe);const value=getComputedStyle(probe).color;probe.remove();return value;};return {value:e.value,max:e.max,state:e.dataset.state,accent:s.accentColor,ruby:color('--ruby'),pumpkin:color('--pumpkin')};});
 const {data,info}=await sharp(await p.screenshot()).removeAlpha().raw().toBuffer({resolveWithObject:true});const wanted=values.accent.match(/\d+/g).map(Number);const pixels=[];
 for(let x=0;x<info.width;x++){const offset=(Math.floor(info.height/2)*info.width+x)*info.channels;pixels.push([...data.subarray(offset,offset+3)]);}
 const filled=pixels.filter(rgb=>rgb.every((n,i)=>n===wanted[i])).length;assert(values.value===0 || filled>0,'Rendered fill matches semantic accent');assert(Math.abs(filled/info.width-values.value/values.max)<.04,'Rendered processed fraction');
 return {...values,fill:values.accent,filledPixels:filled,width:info.width,track:JSON.stringify(pixels.at(-1))};
};
const screenshot=async(name,width)=>{await page.evaluate(()=>document.fonts.ready);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,name+' overflow '+width);await page.screenshot({path:output+'/'+name+'-'+width+'.png',fullPage:true});};
const cards=async name=>{const values=await page.locator('.card:visible').evaluateAll(es=>es.map(e=>{const c=getComputedStyle(e);return {classes:e.className,border:c.borderTopWidth,color:c.borderTopColor,stat:e.classList.contains('stat')};}));for(const v of values)if(!v.stat){assert.equal(v.border,'1px',name+': '+v.classes);assert.notEqual(v.color,'rgba(0, 0, 0, 0)');}return values;};
const jobs=[['Populate missing scores','missing-maintenance-heading'],['Refresh scores','refresh-maintenance-heading'],['Refresh OMDb metadata','metadata-maintenance-heading'],['Fill missing TMDB metadata','tmdb-maintenance-heading'],['Refresh TMDB enrichment','tmdb-enrichment-heading'],['Refresh MDBList enrichment','mdblist-enrichment-heading']];
try{
 if(!process.env.BOOKCLUB_ADMIN_AUTH_ONLY) for(const width of [320,390,720,951,1440]){
  await page.setViewportSize({width,height:900});await page.goto('http://localhost:4173/#/admin');await page.reload();await page.getByRole('heading',{name:'Swap current turn',exact:true}).waitFor();
  const form=page.locator('.rotation-swap-form');await form.locator('select').selectOption('classics');
  const swap=await form.evaluate(e=>{const r=e.getBoundingClientRect(),b=e.querySelector('button').getBoundingClientRect(),s=getComputedStyle(e.querySelector('button'));return {form:r.toJSON(),button:b.toJSON(),padding:s.padding};});assert.equal(swap.button.left,swap.form.left);assert(swap.button.width<swap.form.width);assert.equal(swap.button.height,46);assert(await form.getByRole('button',{name:'Swap turns',exact:true}).isEnabled());
  samples.push({width,swap,cards:await cards('Admin')});await screenshot('admin',width);
  for(const [label,id] of jobs){
   await page.evaluate(()=>localStorage.clear());await page.goto('http://localhost:4173/?audit=operations#/admin');await page.reload();const card=page.locator('section.card').filter({has:page.locator('#'+id)});
   await card.getByRole('button',{name:label,exact:true}).click();await page.waitForFunction(()=>typeof window.finishBatch==='function');await page.evaluate(()=>window.finishBatch(false));await page.waitForFunction(()=>typeof window.finishBatch==='function');
   const progress=card.locator('progress');const normal=await progressSample(progress);assert.equal(normal.state,'normal');assert(normal.value>0&&normal.value<normal.max);assert.equal(normal.fill,normal.pumpkin);
   await page.evaluate(()=>window.finishBatch(true));await progress.locator('xpath=.').waitFor();await page.waitForFunction(id=>document.querySelector('#'+id).closest('section').querySelector('progress').dataset.state==='interrupted',id);
   const interrupted=await progressSample(progress);assert(interrupted.value>=normal.value&&interrupted.value<interrupted.max);assert.equal(interrupted.fill,interrupted.ruby);assert.notEqual(interrupted.fill,normal.fill);assert.equal(interrupted.track,normal.track);samples.push({width,label,normal,interrupted});await screenshot(id+'-interrupted',width);
   // A new run clears the failed colour before its next response.
   const start=card.locator('button').first();await start.click();await page.waitForFunction(()=>typeof window.finishBatch==='function');assert.equal(await card.locator('progress[data-state="interrupted"]').count(),0);await card.getByRole('button',{name:'Stop after this batch',exact:true}).click();await page.evaluate(()=>window.finishBatch(false));await card.getByRole('button',{name:'Stop after this batch',exact:true}).waitFor({state:'hidden'});assert.equal((await progressSample(progress)).state,'normal');
  }
  for(const route of ['home','history','builder','seen','classics','event','movie/a','metrics']){
   await page.evaluate(route=>location.hash='/'+route,route);await page.waitForTimeout(160);await page.locator('main .loading-placeholder:visible').waitFor({state:'hidden'});
   const measured=await cards(route);samples.push({width,route,cards:measured});
   if(route==='home'){const stats=await page.locator('.stats-grid .stat').evaluateAll(es=>es.map(e=>({top:getComputedStyle(e).borderTopWidth,right:getComputedStyle(e).borderRightWidth,bottom:getComputedStyle(e).borderBottomWidth})));assert.equal(stats.length,9);for(const s of stats)assert.deepEqual(s,{top:'0px',right:'0px',bottom:'0px'});}
   if(route==='metrics'){const flat=await page.locator('.metrics-content section:not(.card)').evaluateAll(es=>es.map(e=>{const c=getComputedStyle(e);return {left:c.borderLeftWidth,right:c.borderRightWidth,bottom:c.borderBottomWidth,top:c.borderTopWidth};}));assert(flat.length>0);for(const b of flat){assert.equal(b.left,'0px');assert.equal(b.right,'0px');assert.equal(b.bottom,'0px');assert(['0px','1px'].includes(b.top));}samples.push({width,flatMetrics:flat});}
   await screenshot(route.replace('/','-'),width);
  }
 }
 for(const width of [320,390,720,951,1440]) for(const gate of ['signin','avatar']){
  await page.setViewportSize({width,height:900});await page.goto('http://localhost:4173/?audit='+gate);await page.reload();await page.locator('.card').first().waitFor();const measured=await cards(gate);assert(measured.length>0);samples.push({width,gate,cards:measured});await screenshot(gate,width);
 }
 assert.deepEqual(errors,[]);fs.writeFileSync(output+(process.env.BOOKCLUB_ADMIN_AUTH_ONLY?'/auth-measurements.json':'/measurements.json'),JSON.stringify({samples,errors,blocked},null,2));console.log('Admin jobs, swap geometry and card-border checks passed at all five widths.');
}finally{await browser.close();}
