import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { metricsFixture } from './metrics-fixture.ts';
import { rankMovie } from '../shared/ranking.ts';
const {chromium}=await import(process.env.BOOKCLUB_PLAYWRIGHT_MODULE || '../.verification/node_modules/playwright/index.mjs');
const browser=await chromium.launch({executablePath:process.env.BOOKCLUB_BROWSER_PATH || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
const context=await browser.newContext();const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const catalog=metricsFixture();catalog.movies.forEach((m,i)=>{m.classic=true;m.seen=catalog.members.map(member=>({member_id:member.id,seen:0,updated_at:''}));m.ranking=rankMovie(m.scores,m.seen,catalog.members);m.release_date=i<2?'2025-04-01':null;});
catalog.cycles=[{id:'c55',ordinal:55,title:null,rough_date:'2026-10-01',import_source:null,import_key:null,created_at:'',updated_at:''}];
catalog.sessions=catalog.sessions.filter(s=>!s.deleted_at).map((s,i)=>({...s,cycle_id:'c55',cycle_slot:i+1,completed_turn_version:i}));
catalog.members[1].display_name='A member with an exceptionally long recorded name';
catalog.sessions[0].date_precision='cycle_rough';
catalog.movies[3].director=null;
const pending=Array.from({length:7},(_,i)=>{const movie={...catalog.movies[0],id:'pending-'+i,title:i===0?'A long unseen film title with nine genuine source scores':`Unanswered film ${i}`,director:i%2?'A very long known director name that wraps beside the fixed poster':null,seen:catalog.members.slice(1).map(member=>({member_id:member.id,seen:0,updated_at:''})),scores:[...catalog.movies[0].scores,...catalog.movies[1].scores,...catalog.movies[3].scores]};movie.ranking=rankMovie(movie.scores,movie.seen,catalog.members);return movie;});catalog.movies.push(...pending);
const seenFilm={...catalog.movies[3],id:'seen-film',title:'A previously seen candidate',seen:catalog.members.map(member=>({member_id:member.id,seen:1,updated_at:''}))};seenFilm.ranking=rankMovie(seenFilm.scores,seenFilm.seen,catalog.members);catalog.movies.push(seenFilm);
catalog.movies[0].au_classification='M';
catalog.movies[0].au_watch_offers=[{service_id:'a',name:'Apple TV+',access_type:'subscription',link:null},{service_id:'b',name:'Apple TV',access_type:'subscription',link:null},{service_id:'c',name:'Amazon Prime Video',access_type:'subscription',link:null},{service_id:'d',name:'Apple TV Store',access_type:'rent',link:null},{service_id:'e',name:'Google Play Movies',access_type:'rent',link:null},{service_id:'f',name:'Netflix',access_type:'buy',link:null}];
catalog.movies[1].au_watch_offers=[{service_id:'a',name:'Apple TV Store',access_type:'buy',link:null}];
catalog.movies[0].au_watch_offers.push({service_id:'ads',name:'Synthetic ads provider',access_type:'ads',link:null});
let set={id:'private',owner_member_id:'m1',title:'Synthetic private set',notes:'Preserved',movie_ids:['a','b'],revision:1,created_at:'2026-10-01',updated_at:''};
const requests=[];
await context.addInitScript(()=>localStorage.setItem('bookclub.dev-member','m1'));
await context.route('**/api/v1/**',async route=>{
 const path=new URL(route.request().url()).pathname,method=route.request().method();let data;requests.push({path,method});
 if(path.endsWith('/health'))data={status:'ok',environment:'local',authenticationRequired:false,googleAuthConfigured:false,demo:true};
 else if(path.endsWith('/auth/me'))data={viewer:{...catalog.members[0],role:'member'}};
 else if(path.endsWith('/rotation'))data={id:1,nominal_slot:1,cycle_id:'c55',version:0,updated_at:''};
 else if(path.endsWith('/catalog/compact'))data={...catalog,sessions:catalog.sessions.map(({movies,...session})=>({...session,movie_ids:movies.map(m=>m.id)}))};
 else if(path.endsWith('/builders')&&method==='GET')data=set?[set]:[];
 else if(path.endsWith('/builders')&&method==='POST'){set={...route.request().postDataJSON(),id:'private',owner_member_id:'m1',notes:null,revision:1,created_at:'2026-10-01',updated_at:''};data=set;}
 else if(path.endsWith('/builders/private')&&method==='PUT'){set={...set,...route.request().postDataJSON(),revision:set.revision+1};data=set;}
 else if(path.endsWith('/builders/private')&&method==='DELETE'){set=null;data=null;}
 else if(path.endsWith('/search')){const query=new URL(route.request().url()).searchParams.get('q');const films=query==='empty'?[]:query==='one'?[catalog.movies[0]]:catalog.movies.slice(0,8);data={local:films.map(m=>({id:m.id,title:m.title,year:m.year,tmdbId:null,poster:null})),external:[],lookup:{available:true,message:null}};}
 else if(path.includes('/seen/')&&method==='PUT'){const body=route.request().postDataJSON(),movie=catalog.movies.find(m=>path.includes('/'+m.id+'/seen'));const memberId=path.split('/').at(-1);movie.seen=[...movie.seen.filter(a=>a.member_id!==memberId),{member_id:memberId,seen:body.seen===true?1:body.seen===false?0:body.seen,updated_at:''}];movie.ranking=rankMovie(movie.scores,movie.seen,catalog.members);data={...movie,appearances:[]};}
 else if(path.includes('/movies/')){const m=catalog.movies.find(m=>path.endsWith('/'+m.id));assert(m,path);data={...m,appearances:[]};}
 else throw Error(`Unexpected synthetic request: ${method} ${path}`);
 await route.fulfill({json:{data}});
});
await context.route('**/*',route=>['localhost','127.0.0.1'].includes(new URL(route.request().url()).hostname)?route.fallback():route.abort());
const out='.verification/builder-classics-seen';await fs.mkdir(out,{recursive:true});const measurements=[];
const go=async path=>{await page.evaluate(p=>location.hash='/'+p,path);await page.locator('main .loading-placeholder:visible').waitFor({state:'hidden'});};
const shot=async(name,width)=>{await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`${out}/${name}-${width}.png`,fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${name} ${width}: overflow`);};
const search=async query=>{await page.getByRole('textbox',{name:'Search films',exact:true}).fill(query);await page.getByRole('textbox',{name:'Search films',exact:true}).press('Enter');await page.locator('.search-row,.empty-state').last().waitFor();};
const compactCheck=async()=>{
 const results=await page.locator('.candidate-film:visible').evaluateAll(es=>es.map(e=>{const copy=e.querySelector('.movie-copy'),p=e.querySelector('.poster').getBoundingClientRect(),count=e.querySelector('.compact-seen-summary'),c=count.getBoundingClientRect();return {texts:[...copy.children].map(c=>c.textContent),copies:e.querySelectorAll('.compact-seen-summary').length,poster:p.toJSON(),count:c.toJSON()};}));
 for(const r of results){assert.equal(r.copies,1);assert.match(r.texts.at(-1),/Seen.*Haven't.*Unknown/);assert.equal(r.poster.width,56);assert.equal(r.poster.height,84);}
 const infos=await page.locator('.source-scores-summary:visible').evaluateAll(es=>es.map(e=>{const b=e.querySelector('button').getBoundingClientRect(),svg=e.querySelector('svg').getBoundingClientRect(),row=e.querySelector('p').getBoundingClientRect(),owner=e.closest('.rank-card,.classics-ranking-row'),r=owner.getBoundingClientRect(),count=owner.querySelector('.compact-seen-summary').getBoundingClientRect();return {b:b.toJSON(),svg:svg.toJSON(),row:row.toJSON(),owner:r.toJSON(),count:count.toJSON()};}));
 for(const r of infos){assert(r.b.width>=44&&r.b.height>=44);assert(r.b.top>=r.owner.top&&r.b.left>=r.owner.left&&r.b.right<=r.owner.right&&r.b.bottom<=r.row.top);assert(Math.abs(r.svg.right-r.row.right)<1);assert(Math.abs(r.svg.bottom-r.count.bottom)<1);}
 return {results,infos};
};
try{
 for(const width of [320,390,720,951,1440]){
  // Reset only fictional in-memory fixture responses for each viewport.
  set={id:'private',owner_member_id:'m1',title:'Synthetic private set',notes:'Preserved',movie_ids:['a','b'],revision:1,created_at:'2026-10-01',updated_at:''};for(const m of pending){m.seen=m.seen.filter(a=>a.member_id!=='m1');m.ranking=rankMovie(m.scores,m.seen,catalog.members);}
  await page.setViewportSize({width,height:900});
  for(const count of [1,2,3,4]){
   set.movie_ids=catalog.movies.slice(0,count).map(m=>m.id);catalog.movies[0].title='A very long preview film name that must truncate accessibly';catalog.movies[0].assets=[];
   await page.goto('http://localhost:4173/#/builder');await page.reload();await page.getByRole('button',{name:'Open set',exact:true}).waitFor();
   const tiles=await page.locator('.builder-poster-film').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect(),p=e.querySelector('.poster').getBoundingClientRect();return {r:r.toJSON(),p:p.toJSON(),href:e.getAttribute('href'),label:e.getAttribute('aria-label'),title:e.querySelector('.builder-poster-title').title};}));
   assert.equal(tiles.length,count);for(const tile of tiles){assert(Math.abs(tile.r.top-tiles[0].r.top)<1);assert(Math.abs(tile.r.width-tiles[0].r.width)<1);assert(Math.abs(tile.p.height/tile.p.width-1.5)<.02);assert.equal(tile.label,tile.title);}
   const reads=requests.filter(r=>r.path.endsWith('/builders')&&r.method==='GET').length;
   const link=page.locator('.builder-poster-film').first();await link.focus();assert(await link.evaluate(e=>getComputedStyle(e).outlineStyle!=='none'));await page.keyboard.press('Enter');await page.getByRole('button',{name:'Back',exact:true}).waitFor();assert.equal(await page.evaluate(()=>location.hash),'#/movie/'+catalog.movies[0].id);
   await page.goBack();await page.getByRole('button',{name:'Open set',exact:true}).waitFor();await page.goForward();await page.getByRole('button',{name:'Back',exact:true}).waitFor();await page.getByRole('button',{name:'Back',exact:true}).click();await page.getByRole('button',{name:'Open set',exact:true}).waitFor();
   await page.setViewportSize({width,height:400});await page.evaluate(()=>scrollTo(0,80));const originScroll=await page.evaluate(()=>scrollY);
   await page.locator('.builder-poster-film').first().dispatchEvent('click');await page.getByRole('button',{name:'Back',exact:true}).click();await page.getByRole('button',{name:'Open set',exact:true}).waitFor();await page.waitForFunction(y=>Math.abs(scrollY-y)<1,originScroll);assert(await page.locator('.page-heading h1').evaluate(e=>document.activeElement===e));await page.setViewportSize({width,height:900});
   assert.equal(requests.filter(r=>r.path.endsWith('/builders')&&r.method==='GET').length,reads);await shot('builder-preview-'+count,width);
  }
  set.movie_ids=['a','b'];
  await page.setViewportSize({width,height:900});await page.goto('http://localhost:4173/#/builder');await page.reload();await page.getByRole('button',{name:'Open set',exact:true}).waitFor();await page.evaluate(()=>document.fonts.ready);await shot('builder-list',width);
  await page.getByRole('button',{name:'New set',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Delete set',exact:true}).count(),0);await shot('builder-new',width);await page.getByRole('button',{name:'All sets',exact:true}).click();
  await page.getByRole('button',{name:'Open set',exact:true}).click();assert.deepEqual(await page.locator('.builder-editor-actions button').allTextContents(),['All sets','Delete set','Use set','Save set']);assert.equal(await page.locator('.builder-delete').count(),0);
  const actions=await page.locator('.builder-editor-actions').evaluate(e=>{const r=e.getBoundingClientRect(),left=e.firstElementChild.getBoundingClientRect(),group=e.lastElementChild.getBoundingClientRect();return {row:r.toJSON(),left:left.toJSON(),group:group.toJSON(),buttons:[...e.querySelectorAll('button')].map(b=>b.getBoundingClientRect().toJSON())};});assert.equal(actions.left.left,actions.row.left);assert(Math.abs(actions.group.right-actions.row.right)<1);for(const b of actions.buttons)assert(b.width>=44&&b.height>=44&&b.right<=actions.row.right);
  const identity=page.locator('.builder-lineup .movie-link').first();await identity.hover();const geometry=await identity.evaluate(e=>{const r=e.getBoundingClientRect(),n=e.querySelector('.position').getBoundingClientRect();return {link:r.toJSON(),number:n.toJSON(),hover:getComputedStyle(e).backgroundColor,nested:e.querySelectorAll('button,a').length};});assert.equal(geometry.link.left,geometry.number.left);assert.equal(geometry.nested,0);assert.notEqual(geometry.hover,'rgba(0, 0, 0, 0)');await page.keyboard.press('Tab');await identity.focus();assert(await identity.evaluate(e=>getComputedStyle(e).outlineStyle!=='none'));assert(!(await page.locator('.builder-lineup').innerText()).includes('With ads'));assert.equal(catalog.movies[0].au_watch_offers.filter(o=>o.access_type==='ads').length,1);
  const av=await page.locator('.builder-lineup .au-availability p').evaluateAll(es=>es.map(e=>({text:e.textContent,font:getComputedStyle(e).font,color:getComputedStyle(e).color})));assert.deepEqual(av.map(e=>e.text),['Stream: Apple \u00b7 Prime','Rent: Apple \u00b7 Google']);assert.equal(av[0].font,av[1].font);assert.equal(av[0].color,av[1].color);assert(await page.locator('.builder-lineup').innerText().then(t=>t.includes('No cached Australian streaming or rental options to display')));await shot('builder-editor',width);
  const before=requests.filter(r=>r.method==='DELETE').length;await page.getByRole('button',{name:'Delete set',exact:true}).click();await page.getByRole('region',{name:'Delete private set'}).waitFor();assert.equal(requests.filter(r=>r.method==='DELETE').length,before);await shot('builder-delete-confirm',width);await page.getByRole('button',{name:'Keep set',exact:true}).click();
  await search('one');await page.locator('.search-row').first().waitFor();assert.equal(await page.locator('.search-pagination').count(),0);assert.equal(await page.locator('.search-row .search-history-badge').count(),1);
  const searchGeometry=await page.locator('.film-search-form').evaluate(e=>{const r=e.getBoundingClientRect(),b=e.querySelector('button').getBoundingClientRect();return {form:r.toJSON(),button:b.toJSON()};});assert(Math.abs(searchGeometry.button.right-searchGeometry.form.right)<1);assert(searchGeometry.button.width<searchGeometry.form.width);assert.equal(searchGeometry.button.height,46);
  const badge=await page.locator('.search-history-badge').evaluate(e=>{const r=e.getBoundingClientRect(),owner=e.parentElement.getBoundingClientRect(),s=getComputedStyle(e);return {r:r.toJSON(),owner:owner.toJSON(),border:s.borderColor,color:s.color,ruby:getComputedStyle(document.documentElement).getPropertyValue('--ruby').trim(),background:s.backgroundColor,whiteSpace:s.whiteSpace};});assert.equal(badge.border,badge.color);assert.equal(badge.background,'rgba(0, 0, 0, 0)');assert.equal(badge.whiteSpace,'nowrap');assert(badge.r.right<=badge.owner.right+.5);await shot('builder-one-result',width);
  await search('many');await page.getByRole('button',{name:'Next',exact:true}).click();assert.match(await page.locator('.search-pagination').innerText(),/Page 2 of 2/);await shot('builder-multiple-results',width);await page.getByRole('button',{name:'Previous',exact:true}).click();await search('empty');assert.equal(await page.locator('.search-pagination').count(),0);await shot('builder-empty-results',width);
  await page.getByRole('button',{name:'Save set',exact:true}).click();await page.getByRole('button',{name:'Open set',exact:true}).waitFor();await page.getByRole('button',{name:'Open set',exact:true}).click();await page.getByRole('button',{name:'Use set',exact:true}).click();await page.getByRole('heading',{name:'Use Synthetic private set?',exact:true}).waitFor();await shot('builder-use-confirm',width);
  await go('classics');const tabs=await page.locator('.classics-filters button').evaluateAll(es=>es.map(e=>({font:getComputedStyle(e).fontSize,r:e.getBoundingClientRect().toJSON(),scroll:e.scrollWidth,client:e.clientWidth})));for(const t of tabs){assert.equal(t.font,'16px');assert.equal(t.r.height,44);assert(t.scroll<=t.client);}
  const identities=[];for(const state of ['Ranked','Unranked','Seen']){await page.getByRole('button',{name:new RegExp('^'+state+':')}).click();await page.locator('.candidate-film').first().waitFor();identities.push({state,...await compactCheck()});await shot('classics-'+state.toLowerCase(),width);}
  await page.getByRole('button',{name:/^Ranked:/}).click();const help=page.getByRole('button',{name:'Explain score abbreviations',exact:true}).first();await help.focus();await page.keyboard.press('Enter');await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');assert(await help.evaluate(e=>document.activeElement===e));
  await go('seen');await page.locator('.answer-card').waitFor().catch(async error=>{console.error({width,pending:pending.map(m=>m.seen),body:await page.locator('body').innerText()});throw error;});await shot('seen-active',width);assert.equal(await page.getByRole('button',{name:'No, not yet',exact:true}).count(),1);assert.equal(await page.getByText('You can correct your recent answers below.',{exact:true}).count(),0);
  for(let i=0;i<7;i++){const saved=page.waitForResponse(r=>r.url().includes('/seen/')&&r.request().method()==='PUT');await page.getByRole('button',{name:'Yes, seen it',exact:true}).click();await saved;await page.waitForFunction(n=>document.querySelector('.recent-list').textContent.includes('Unanswered film '+n)||document.querySelector('.recent-list').textContent.includes('nine genuine'),i);}
  await page.getByRole('heading',{name:'All caught up',exact:true}).waitFor();assert.equal(await page.getByRole('link',{name:'Explore Classics',exact:true}).count(),0);assert.equal(await page.locator('.recent-answer').count(),5);await shot('seen-completed-recent',width);await page.locator('.recent-pagination').getByRole('button',{name:'Next',exact:true}).click();assert.equal(await page.locator('.recent-answer').count(),2);await shot('seen-recent-page2',width);const corrected=page.waitForResponse(r=>r.url().includes('/seen/')&&r.request().method()==='PUT');await page.getByRole('button',{name:'Change to No',exact:true}).first().click();await corrected;await page.locator('.recent-answer').filter({hasText:'Not seen'}).waitFor();await shot('seen-corrected',width);
  await go('home');await page.locator('.home-rank-card').first().waitFor();await compactCheck();await shot('home',width);await go('history');await page.locator('.history-event').first().waitFor();assert(await page.locator('.history-event-heading').evaluateAll(es=>es.every(e=>e.firstElementChild.tagName==='H3')));await shot('history',width);
  measurements.push({width,actions,av,searchGeometry,badge,tabs,identities});
 }
 assert.deepEqual(errors,[]);await fs.writeFile(`${out}/results.json`,JSON.stringify({measurements,errors,requests},null,2));console.log('Builder/Classics/Seen rendered checks passed at five widths.');
}finally{await browser.close();}
