import { afterEach,expect,it,vi } from 'vitest';
import { disposableD1 } from './d1';
import { MaintenanceJobs } from '../worker/src/maintenance-jobs';
import { Repository } from '../worker/src/repository';
import { UnifiedMaintenanceService } from '../worker/src/unified-maintenance';
import { planMaintenance, type MaintenanceOperation } from '../shared/maintenance-plan';
import { tmdbEnrichmentFixture,mdbEnrichmentFixture } from './enrichment-fixtures';
import type { Env } from '../worker/src/http';
import { maintenanceJobDatabase } from '../worker/src/maintenance-job-db';
import { classifyMaintenanceFailure } from '../worker/src/maintenance-failure';
const fixtures:ReturnType<typeof disposableD1>[]=[];
function fixture(n=3){const local=disposableD1();fixtures.push(local);for(let i=1;i<=n;i++){local.sqlite.prepare('INSERT INTO movies(id,title) VALUES(?,?)').run(`film-${i}`,`Film ${i}`);local.sqlite.prepare("INSERT INTO movie_external_ids VALUES(?,'imdb',?)").run(`film-${i}`,`tt${String(i).padStart(7,'0')}`);local.sqlite.prepare("INSERT INTO movie_external_ids VALUES(?,'tmdb',?)").run(`film-${i}`,String(i));local.sqlite.prepare("INSERT INTO classics(movie_id,source) VALUES(?,'member-added')").run(`film-${i}`);}
  const env:Env={DB:local.db,APP_ENV:'local',LOCAL_WRITE_BYPASS:'true',ALLOWED_ORIGINS:'',TMDB_READ_TOKEN:'fictional',OMDB_API_KEY:'fictional',MDBLIST_API_KEY:'fictional'};return {local,env,jobs:new MaintenanceJobs(env),repo:new Repository(local.db)};}
afterEach(()=>{fixtures.splice(0).forEach(f=>f.sqlite.close());vi.unstubAllGlobals();vi.useRealTimers();});
function upstream(poison=0){const calls:string[]=[];vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const u=new URL(String(input));if(u.hostname==='api.mdblist.com'){calls.push('mdblist');const ids=init?.body?JSON.parse(String(init.body)).ids:[u.pathname.split('/').at(-2)];return Response.json(ids.map((id:string)=>Number(id.slice(2))===poison?{ids:{imdb:id},ratings:'malformed'}:{...mdbEnrichmentFixture(id,Number(id.slice(2))),ids:{imdb:id}}));}
    const id=u.hostname==='www.omdbapi.com'?Number(u.searchParams.get('i')!.slice(2)):Number(u.pathname.split('/').at(-1));calls.push(`${u.hostname}:${id}`);if(id===poison)return Response.json({malformed:true});
    if(u.hostname==='www.omdbapi.com')return Response.json({Response:'True',imdbID:u.searchParams.get('i'),Title:'Film',Year:'2000',Runtime:'100 min',Genre:'Drama',Director:'Director',Awards:'N/A',imdbRating:'8',Metascore:'80',Ratings:[]});const data=tmdbEnrichmentFixture(id);data.external_ids.imdb_id=`tt${String(id).padStart(7,'0')}`;return Response.json({...data,belongs_to_collection:null});}));return calls;}
async function ready(jobs:MaintenanceJobs,id:string,intent:Parameters<MaintenanceJobs['create']>[1],operation:Parameters<MaintenanceJobs['create']>[2],legacy?:Parameters<MaintenanceJobs['create']>[3]) {
 let job=await jobs.create(id,intent,operation,legacy);const claim=await jobs.claim(id,'Planning test');
 try{while(job.planning&&job.planning.stage!=='complete')job=await jobs.plan(id,claim.token);}finally{await jobs.release(id,claim.token);}return job;
}
async function drain(jobs:MaintenanceJobs,id:string,token:string){for(let i=0;i<1000;i++){const current=await jobs.status(id);const status=await (current.planning&&current.planning.stage!=='complete'?jobs.plan(id,token):jobs.step(id,token));if(['completed','completed_with_issues','failed','awaiting_cooldown','paused'].includes(status.state))return status;}throw Error('Job did not terminate');}

it.each(['populate','refresh'] as const)('persists %s success and failures across devices without poison replay',async intent=>{const {jobs,env,local}=fixture(),calls=upstream(2),id=crypto.randomUUID();await ready(jobs,id,intent,'all');const first=await jobs.claim(id,'Browser one');const complete=await drain(jobs,id,first.token);expect(complete.state).toBe('completed_with_issues');expect(complete.counts.deferred).toBe(3);expect(complete.counts.successful).toBe(6);expect(complete.phase).toBe('collections');await jobs.release(id,first.token);
  const other=new MaintenanceJobs(env),before=calls.length;expect((await other.list()).jobs.some(j=>j.id===id)).toBe(true);expect((await other.status(id)).issues).toHaveLength(3);await expect(other.claim(id,'Browser two')).rejects.toMatchObject({code:'JOB_COMPLETE'});expect(calls).toHaveLength(before);expect(local.sqlite.prepare("SELECT count(*) AS n FROM maintenance_job_units WHERE status='successful'").get()?.n).toBe(6);
  await other.retry(id);expect((await other.status(id)).counts.pending).toBe(0);expect(calls).toHaveLength(before);
});
it.each([1,2,3])('isolates bad OMDb film %i before and after valid films',async poison=>{const {repo,env}=fixture();upstream(poison);const service=new UnifiedMaintenanceService(repo,env),catalog=await repo.catalog(),coverage=await service.status(null),units=planMaintenance(catalog,coverage,'refresh',['omdb-metadata']).units;const result=await service.execute('refresh',units,new Date().toISOString());expect(result.results).toHaveLength(3);expect(result.results.filter(r=>r.status==='failed')).toHaveLength(1);expect(result.stopped).toBeUndefined();});
it.each((['populate','refresh'] as const).flatMap(intent=>(['scores','omdb-metadata','tmdb-metadata','tmdb-enrichment','mdblist-enrichment','tmdb-collections','omdb-awards'] satisfies MaintenanceOperation[]).flatMap(operation=>[1,2,3].map(poison=>({intent,operation,poison})))))('$intent/$operation isolates poisoned record $poison and attempts its valid peers',async({intent,operation,poison})=>{
 const {repo,env}=fixture();upstream(poison);const service=new UnifiedMaintenanceService(repo,env),plan=planMaintenance(await repo.catalog(),await service.status(null),intent,[operation]);
 const batches=operation==='scores'?plan.batches.filter(b=>b[0].provider==='mdblist'):plan.batches;
 const results=[];for(const batch of batches){const response=await service.execute(intent,batch,new Date().toISOString());expect(response.stopped).not.toBe(true);results.push(...response.results);}
 expect(results).toHaveLength(3);expect(results.filter(r=>r.status==='failed')).toHaveLength(1);expect(results.filter(r=>r.status==='updated'||r.status==='no_change')).toHaveLength(2);
});
it.each(['scores','omdb-metadata','tmdb-metadata','tmdb-enrichment','mdblist-enrichment','tmdb-collections','omdb-awards'] satisfies MaintenanceOperation[])('retains operation %s scope and read-only status makes no requests',async operation=>{const {jobs,local}=fixture(1),calls=upstream(),id=crypto.randomUUID();const job=await ready(jobs,id,'refresh',operation);await jobs.status(id);await jobs.list();expect(calls).toHaveLength(0);const units=local.sqlite.prepare('SELECT operations_json FROM maintenance_job_units WHERE job_id=?').all(id);expect(units.every(u=>JSON.parse(String(u.operations_json)).every((o:string)=>o===operation))).toBe(true);expect(job.started_at).toBeTruthy();});
it('MDBList saves nine valid entries and defers one malformed entry with one request',async()=>{const {repo,env}=fixture(10),calls=upstream(5),service=new UnifiedMaintenanceService(repo,env);const units=planMaintenance(await repo.catalog(),await service.status(null),'refresh',['mdblist-enrichment']).units;const result=await service.execute('refresh',units,new Date().toISOString());expect(result.results.filter(r=>r.status==='failed')).toHaveLength(1);expect(result.results).toHaveLength(10);expect(result.requests).toBe(1);expect(calls).toHaveLength(1);});
it('uses conditional lease ownership, excludes duplicate steps, and fences stale writes after expiry',async()=>{const {jobs,env,local}=fixture(1);upstream();const id=crypto.randomUUID();await ready(jobs,id,'refresh','omdb-metadata');const results=await Promise.allSettled([jobs.claim(id,'one'),jobs.claim(id,'two')]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);const token=(results.find(r=>r.status==='fulfilled') as PromiseFulfilledResult<{token:string}>).value.token;
  local.sqlite.prepare('UPDATE maintenance_lease SET execution=?').run('old-execution');await expect(jobs.step(id,token)).rejects.toMatchObject({code:'LEASE_LOST'});const stale=maintenanceJobDatabase(env.DB,id,token,'old-execution');local.sqlite.exec('UPDATE maintenance_lease SET expires_at=0');const taken=await jobs.claim(id,'new');expect(taken.token).not.toBe(token);await expect(stale.prepare("UPDATE movies SET title='stale'").run()).rejects.toThrow('MAINTENANCE_LEASE_LOST');expect(local.sqlite.prepare('SELECT title FROM movies').get()?.title).toBe('Film 1');await expect(jobs.step(id,token)).rejects.toMatchObject({code:'LEASE_LOST'});
});
it('recognizes committed evidence from a lost response before another device resumes',async()=>{const {jobs,env,local,repo}=fixture(1),calls=upstream(),id=crypto.randomUUID();const job=await ready(jobs,id,'refresh','omdb-metadata');const unit=planMaintenance(await repo.catalog(),await new UnifiedMaintenanceService(repo,env).status(null),'refresh',['omdb-metadata']).units[0];await new UnifiedMaintenanceService(repo,env).execute('refresh',[unit],job.started_at);local.sqlite.exec("UPDATE maintenance_job_units SET status='running',attempts=1");const lease=await jobs.claim(id,'new device');const complete=await drain(jobs,id,lease.token);expect(complete.state).toBe('completed');expect(calls).toHaveLength(1);});
it('stops after the current batch and resumes only unfinished scope',async()=>{const {jobs}=fixture(3),calls=upstream(),id=crypto.randomUUID();await ready(jobs,id,'refresh','omdb-metadata');const lease=await jobs.claim(id,'one');await jobs.step(id,lease.token);expect(calls).toHaveLength(2);await jobs.stop(id);expect((await jobs.step(id,lease.token)).state).toBe('paused');await jobs.release(id,lease.token);const next=await jobs.claim(id,'two');expect((await drain(jobs,id,next.token)).state).toBe('completed');expect(calls).toHaveLength(3);});
it('unknown storage failures remain systemic rather than becoming harmless record failures',()=>{expect(classifyMaintenanceFailure(Error('database unavailable')).category).toBe('systemic');expect(classifyMaintenanceFailure(Error('UNIQUE constraint failed: fictional')).category).toBe('record');});

it('finishes 500 films and 20 rosters despite a poisoned film and collection, without replay on another device',async()=>{
 const {jobs,local,env}=fixture(500);local.sqlite.exec("INSERT INTO members(id,display_name,sort_order,active) VALUES('member','Fictional',1,1);INSERT INTO sessions(id,event_date,date_precision,host_member_id,kind) VALUES('history','2020-01-01','exact','member','hosted')");
 for(let i=1;i<=500;i++)local.sqlite.prepare("INSERT INTO session_movies(session_id,movie_id,position) VALUES('history',?,?)").run(`film-${i}`,i);
 const calls=upstream(138),base=globalThis.fetch;
 vi.stubGlobal('fetch',async(input:RequestInfo|URL,init?:RequestInit)=>{
   const url=new URL(String(input)),id=Number(url.pathname.split('/').at(-1));
   if(url.pathname.includes('/collection/')){calls.push(`roster:${id}`);return Response.json({id,name:`Series ${id}`,parts:id===8?[]:[{id:id*2-1},{id:id*2}]});}
   const response=await base(input,init);
   if(url.hostname!=='api.mdblist.com'&&url.hostname!=='www.omdbapi.com'&&id<=40){const data=await response.json() as Record<string,unknown>;data.belongs_to_collection={id:Math.ceil(id/2),name:`Series ${Math.ceil(id/2)}`};return Response.json(data);}
   return response;
 });
 const id=crypto.randomUUID();await ready(jobs,id,'refresh','all');const first=await jobs.claim(id,'first device');for(let i=0;i<5;i++)await jobs.step(id,first.token);await jobs.stop(id);await jobs.step(id,first.token);await jobs.release(id,first.token);
 const second=new MaintenanceJobs(env),claim=await second.claim(id,'second device'),complete=await drain(second,id,claim.token);
 expect(complete.state).toBe('completed_with_issues');expect(complete.counts.deferred).toBe(4);expect(complete.counts.successful).toBe(1516);expect(complete.counts.pending+complete.counts.running+complete.counts.blocked).toBe(0);expect(complete.issues.filter(i=>i.movieId==='film-138')).toHaveLength(3);expect(complete.issues.some(i=>i.collectionId===8)).toBe(true);
 expect(calls.filter(c=>c.startsWith('roster:'))).toHaveLength(20);expect(calls.filter(c=>c.includes('omdbapi'))).toHaveLength(500);expect(calls.filter(c=>c==='mdblist')).toHaveLength(50);expect(complete.requests).toBe(calls.length);
 const before=calls.length;await second.step(id,claim.token);expect(calls).toHaveLength(before);
},120000);

it('transient transport failure retries once, succeeds, and counts both requests',async()=>{const {jobs}=fixture(1),calls=upstream(),base=globalThis.fetch;let attempts=0;vi.stubGlobal('fetch',(input:RequestInfo|URL,init?:RequestInit)=>{if(attempts++===0)throw Error('temporary');return base(input,init);});const id=crypto.randomUUID();await ready(jobs,id,'refresh','omdb-metadata');const lease=await jobs.claim(id,'one');const complete=await drain(jobs,id,lease.token);expect(complete.state).toBe('completed');expect(complete.requests).toBe(2);expect(calls).toHaveLength(1);});
it('systemic write failure pauses once, preserves prior evidence and defers ambiguity rather than pretending success',async()=>{const {jobs,local}=fixture(1);upstream();const id=crypto.randomUUID();await ready(jobs,id,'refresh','omdb-metadata');local.sqlite.exec("CREATE TRIGGER reject_metadata BEFORE UPDATE ON movies BEGIN SELECT RAISE(ABORT,'synthetic storage unavailable'); END");const lease=await jobs.claim(id,'one');await expect(jobs.step(id,lease.token)).rejects.toMatchObject({code:'MAINTENANCE_PAUSED'});expect((await jobs.status(id)).state).toBe('failed');expect((await jobs.status(id)).counts.successful).toBe(0);expect(local.sqlite.prepare("SELECT count(*) AS n FROM movie_maintenance_coverage WHERE domain='metadata'").get()?.n).toBe(0);});
it('legacy film-only imports preserve their start and original dimensions without expanding into rosters',async()=>{const {jobs}=fixture(1),calls=upstream(),id=crypto.randomUUID();const imported=await ready(jobs,id,'refresh','all',{id,intent:'refresh',operation:'all',startedAt:'2020-01-01T00:00:00.000Z',phase:'films',filmOnly:true,rosterStartedAt:null,units:[['film-1','omdb','imdb','tt0000001',['omdb-metadata'],[]]],collections:[]});expect(imported.started_at).toBe('2020-01-01T00:00:00.000Z');const claim=await jobs.claim(id,'one');const complete=await drain(jobs,id,claim.token);expect(complete.phase).toBe('films');expect(calls).toHaveLength(1);});
it('rejects tampered legacy identities and provider-incompatible dimensions before requests',async()=>{const {jobs}=fixture(1),calls=upstream(),id=crypto.randomUUID();await expect(jobs.create(id,'refresh','scores',{id,intent:'refresh',operation:'scores',startedAt:'2020-01-01T00:00:00.000Z',phase:'films',filmOnly:false,rosterStartedAt:null,units:[['film-1','omdb','imdb','tt0000001',['scores'],['trakt:rating']]],collections:[]})).rejects.toMatchObject({code:'INVALID_LEGACY_SCOPE'});expect(calls).toHaveLength(0);});

it.each((['populate','refresh'] as const).flatMap(intent=>[1,2,3].map(poison=>({intent,poison}))))('$intent roster queue isolates malformed collection $poison and preserves good previous evidence',async({intent,poison})=>{
 const {jobs,local}=fixture(6);local.sqlite.exec("INSERT INTO members(id,display_name,sort_order,active) VALUES('member','Fictional',1,1);INSERT INTO sessions(id,event_date,date_precision,host_member_id,kind) VALUES('history','2020-01-01','exact','member','hosted')");
 for(let i=1;i<=6;i++){local.sqlite.prepare("INSERT INTO session_movies(session_id,movie_id,position) VALUES('history',?,?)").run(`film-${i}`,i);local.sqlite.prepare('INSERT INTO movie_provider_collections(movie_id,identity_provider,external_id,checked_at,collection_id,collection_name) VALUES(?,?,?,?,?,?)').run(`film-${i}`,'tmdb',String(i),'2000-01-01T00:00:00.000Z',Math.ceil(i/2),'Series');}
 if(intent==='refresh')local.sqlite.prepare("INSERT INTO tmdb_collection_rosters(collection_id,name,checked_at,parts_json,attempted_at,attempt_status) VALUES(?,'Old series','2000-01-01T00:00:00.000Z',?,'2000-01-01T00:00:00.000Z','checked')").run(poison,JSON.stringify([{id:poison*2-1},{id:poison*2}]));
 const calls:number[]=[];vi.stubGlobal('fetch',async(input:RequestInfo|URL)=>{const id=Number(new URL(String(input)).pathname.split('/').at(-1));calls.push(id);return Response.json({id,name:'Series',parts:id===poison?[]:[{id:id*2-1},{id:id*2}]});});
 const id=crypto.randomUUID();await ready(jobs,id,intent,'collection-rosters');const lease=await jobs.claim(id,'one'),complete=await drain(jobs,id,lease.token);expect(complete.state).toBe('completed_with_issues');expect(complete.counts.successful).toBe(2);expect(complete.counts.deferred).toBe(1);expect(calls).toEqual([1,2,3]);if(intent==='refresh')expect(local.sqlite.prepare('SELECT checked_at FROM tmdb_collection_rosters WHERE collection_id=?').get(poison)?.checked_at).toBe('2000-01-01T00:00:00.000Z');
 await jobs.release(id,lease.token);local.sqlite.exec("UPDATE maintenance_job_units SET retry_at='2000-01-01T00:00:00.000Z' WHERE status='deferred'");await jobs.retry(id,[`collection:${poison}`]);const retry=await jobs.claim(id,'two');expect((await drain(jobs,id,retry.token)).state).toBe('completed_with_issues');expect(calls).toEqual([1,2,3,poison]);
});
it('isolates a film-level constraint while continuing both peers',async()=>{const {jobs,local}=fixture();const calls=upstream();local.sqlite.exec("CREATE TRIGGER reject_one BEFORE UPDATE ON movies WHEN OLD.id='film-2' BEGIN SELECT RAISE(ABORT,'CHECK constraint failed: synthetic_record'); END");const id=crypto.randomUUID();await ready(jobs,id,'refresh','omdb-metadata');const lease=await jobs.claim(id,'one');const complete=await drain(jobs,id,lease.token);expect(complete.state).toBe('completed_with_issues');expect(complete.counts.successful).toBe(2);expect(complete.counts.deferred).toBe(1);expect(calls).toHaveLength(3);});
it('Retry failed extends newly eligible rosters without replaying previous film or roster successes',async()=>{
 const {jobs,local}=fixture(4);local.sqlite.exec("INSERT INTO members(id,display_name,sort_order,active) VALUES('member','Fictional',1,1);INSERT INTO sessions(id,event_date,date_precision,host_member_id,kind) VALUES('history','2020-01-01','exact','member','hosted')");for(let i=1;i<=4;i++)local.sqlite.prepare("INSERT INTO session_movies(session_id,movie_id,position) VALUES('history',?,?)").run(`film-${i}`,i);
 const calls=upstream(),base=globalThis.fetch;let poisoned=true;vi.stubGlobal('fetch',async(input:RequestInfo|URL,init?:RequestInit)=>{const url=new URL(String(input)),n=Number(url.pathname.split('/').at(-1));if(url.pathname.includes('/collection/')){calls.push('roster:'+n);return Response.json({id:n,name:'Series',parts:n===1?[{id:1},{id:2}]:[{id:3},{id:4}]});}if(url.hostname==='api.themoviedb.org'){if(n===4&&poisoned){calls.push('poison:4');return Response.json({malformed:true});}const data=await(await base(input,init)).json() as Record<string,unknown>;return Response.json({...data,belongs_to_collection:{id:n<=2?1:2,name:'Series'}});}return base(input,init);});
 const id=crypto.randomUUID();await ready(jobs,id,'refresh','all');const lease=await jobs.claim(id,'one');expect((await drain(jobs,id,lease.token)).counts.deferred).toBe(1);expect(calls.filter(c=>c.startsWith('roster:'))).toEqual(['roster:1']);await jobs.release(id,lease.token);local.sqlite.exec("UPDATE maintenance_job_units SET retry_at='2000-01-01T00:00:00.000Z' WHERE status='deferred'");poisoned=false;const before=calls.length;await jobs.retry(id);const second=await jobs.claim(id,'two');expect((await drain(jobs,id,second.token)).state).toBe('completed');expect(calls.slice(before)).toEqual(['api.themoviedb.org:4','roster:2']);
});
