// Optional local-Vite visual check. Fictional data only; all APIs and external traffic are blocked.
import fs from 'node:fs';
import assert from 'node:assert/strict';
const inventory=JSON.parse(fs.readFileSync('tests/helpers/metrics-inventory.ts','utf8').split('export const metricsInventory = ')[1].split(' as const;')[0]);
const {chromium}=await import(process.env.BOOKCLUB_PLAYWRIGHT_MODULE || '../.verification/node_modules/playwright/index.mjs');
const output='.verification/metrics-staging';fs.mkdirSync(output,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.BOOKCLUB_BROWSER_PATH || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
const page=await browser.newPage(),errors=[],samples=[];
page.on('pageerror',error=>errors.push(error.message));
await page.route('**/*',route=>{const url=new URL(route.request().url());return ['localhost','127.0.0.1'].includes(url.hostname)?route.fallback():route.abort();});
await page.route('**/api/**',route=>{errors.push('Unmocked API request');return route.abort();});
await page.route('**/__dev/**',route=>route.abort());
await page.route(/\/frontend\/api\.ts(?:\?.*)?$/,route=>route.fulfill({contentType:'text/javascript',body:"export const api=globalThis.__auditApi ??= {};export class ApiClientError extends Error {}export const hasSession=()=>true;export const setUnauthorizedHandler=()=>{};export const setDevMember=()=>{};export const clearSession=()=>{};export const storeSession=()=>{};"}));
const source=await(await fetch('http://localhost:4173/frontend/main.tsx')).text(),reactUrl=source.match(/from "([^"\n]+\/react\.js[^"\n]*)"/)[1],domUrl=source.match(/from "([^"\n]+\/react-dom_client\.js[^"\n]*)"/)[1];
await page.route(/\/frontend\/main\.tsx(?:\?.*)?$/,route=>route.fulfill({contentType:'text/javascript',body:`
import React from '${reactUrl}';import ReactDOM from '${domUrl}';import '/style.css';import '/frontend/app.css';
import '/node_modules/@fontsource/lexend-deca/400.css';import '/node_modules/@fontsource/lexend-deca/500.css';import '/node_modules/@fontsource/lexend-deca/600.css';import '/node_modules/@fontsource/lexend-deca/700.css';
import {App} from '/frontend/App.tsx';import {metricsFixture,metricsFilm,metricsEvent,observation} from '/tests/metrics-fixture.ts';import {emptyEnrichmentMovie} from '/shared/metrics-enrichment.ts';import {api} from '/frontend/api.ts';
const catalog=metricsFixture(),data={movies:{},collections:{1:{status:'checked',attempted_at:'2026-01-01',roster:{id:1,name:'Completed fictional collection',checked_at:'2026-01-01',parts:[{id:3,title:'Part 3',release_date:'2000-01-01'},{id:4,title:'Part 4',release_date:'2001-01-01'}]}},2:{status:'checked',attempted_at:'2026-01-01',roster:{id:2,name:'Incomplete fictional collection',checked_at:'2026-01-01',parts:[{id:5,title:'Part 5',release_date:'2000-01-01'},{id:6,title:'Part 6',release_date:'2001-01-01'},{id:99,title:'Announced future film with a very long title that must wrap',release_date:null}]}}}};catalog.members.forEach((m,i)=>m.avatar=i+1);
catalog.movies=Array.from({length:24},(_,i)=>metricsFilm('staging-'+i,{title:'Fictional film '+i+' with a long title for responsive verification',classic:true,au_classification:'M',external_ids:[{provider:'tmdb',external_id:String(i+1)}],year:1920+i*4,runtime:60+i*8,genres:['Action','Adventure','Animation','Comedy','Crime','Drama','Fantasy','Horror'],scores:[observation('metacritic','critic',60,100),observation('imdb','rating',8,10,100+i*100)],seen:catalog.members.map((m,j)=>({member_id:m.id,seen:(i+j)%2,updated_at:''})),au_watch_offers:[{service_id:'1',name:'Netflix',access_type:'subscription',link:null},{service_id:'2',name:'Apple TV Store',access_type:'rent',link:null}]}));
catalog.cycles=Array.from({length:8},(_,i)=>({id:'cycle-'+i,ordinal:i+1,rough_date:'2026-01-01',title:null,import_source:'synthetic',import_key:'cycle-'+i,created_at:'',updated_at:'',classics_first:i===1?1:0}));
catalog.sessions=catalog.cycles.flatMap(c=>Array.from({length:5},(_,i)=>({...metricsEvent(c.id+'-'+i,[catalog.movies[(c.ordinal*2+i)%24],catalog.movies[(c.ordinal*2+i+1)%24]],i+1===(c.classics_first?1:5)?null:'m'+(i===4?1:i+1)),cycle_id:c.id,cycle_slot:i+1})));
for(const [i,movie] of catalog.movies.entries())data.movies[movie.id]={...emptyEnrichmentMovie(),metadata:{original_language:'en',budget:1000000*(i+1),revenue:10000000*(i+1)},keywords:[{provider:'tmdb',name:'time-travel'},{provider:'tmdb',name:'friendship'}],contentRatings:[{certification:['G','PG','M','MA15+','R18+'][i%5],release_type:3}],credits:[...Array.from({length:23},(_,j)=>({kind:'cast',role:'cast',person_id:String(j+1),name:'Fictional actor '+j+' with a long credited name'})),...['writer','screenplay','composer','cinematographer','editor'].map(role=>({kind:'crew',role,person_id:role==='screenplay'?'writer':role,name:'Fictional '+(role==='screenplay'?'writer':role)}))],collection:{status:[2,3,4,5].includes(i)?'checked_present':'checked_none',external_id:String(i+1),checked_at:'2026',collection_id:[2,3].includes(i)?1:[4,5].includes(i)?2:null,collection_name:[2,3,4,5].includes(i)?'Fictional collection':null},awards:{status:'checked_quantified',external_id:'tt'+i,checked_at:'2026',wins:i,nominations:i+2,awards_text:i+' wins & '+(i+2)+' nominations.'}};
data.movies[catalog.movies[22].id].metadata.revenue=data.movies[catalog.movies[23].id].metadata.revenue;
window.enrichmentReads=0;api.health=async()=>({status:'ok',environment:'test',authenticationRequired:true,demo:false});api.me=async()=>({viewer:{...catalog.members[0],role:'member'}});api.catalog=async()=>catalog;api.rotation=async()=>({id:1,nominal_slot:1,cycle_id:null,version:0,updated_at:''});api.builders=async()=>[];api.metricsEnrichment=async()=>{window.enrichmentReads++;return data;};
ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(App));
`}));
try {
 for(const width of [320,390,720,951,1440]){
  await page.setViewportSize({width,height:1000});await page.goto('http://localhost:4173/#/metrics');await page.getByRole('tab',{name:'Breakdowns',exact:true}).click();await page.locator('.staging-report').last().waitFor();await page.locator('.metrics-filters button').first().click();
  assert.equal(await page.locator('.staging-report').count(),11);assert.equal(await page.locator('.staging-cycle').count(),8);assert.equal(await page.locator('.staging-matrix').count(),0);

  const cycle=await page.locator('.staging-cycles').evaluate(e=>({height:e.clientHeight,total:e.scrollHeight,firstFive:[...e.children].slice(0,5).reduce((n,c)=>n+c.getBoundingClientRect().height,0)}));assert(cycle.total>cycle.height);assert(Math.abs(cycle.height-cycle.firstFive)<2);
  await page.locator('.staging-cycles').evaluate(e=>e.scrollTop=e.scrollHeight);assert(await page.locator('.staging-cycle').last().isVisible());
  const axes=await page.locator('[aria-label^="Shared"]').evaluateAll(es=>es.map(e=>e.getAttribute('aria-label')));
  const geometry=await page.locator('.staging-report').evaluateAll(reports=>reports.flatMap(report=>{
    const axis=report.querySelector('.staging-axis'),tracks=[...report.querySelectorAll('.staging-interval,.staging-diverging')];
    if(!axis)return [];const rect=axis.getBoundingClientRect();return tracks.map(track=>{const r=track.getBoundingClientRect();return {report:report.getAttribute('aria-label'),axisLeft:rect.left,axisRight:rect.right,left:r.left,right:r.right};});
  }));
  for(const g of geometry){assert(Math.abs(g.axisLeft-g.left)<1);assert(Math.abs(g.axisRight-g.right)<1);}
  const bars=await page.locator('.staging-paired').evaluateAll(es=>es.map(e=>{const [critic,audience]=e.querySelectorAll('.staging-score-track');return {criticBottom:critic.getBoundingClientRect().bottom,audienceTop:audience.getBoundingClientRect().top,colour:getComputedStyle(audience.firstElementChild).backgroundColor,labels:[...e.children].map(n=>n.textContent)};}));
  bars.forEach(b=>{assert(Math.abs(b.criticBottom-b.audienceTop)<1);assert.equal(b.colour,'rgb(147, 152, 236)');assert(b.labels[3].startsWith('Audience:'));});
  assert.equal(await page.locator('.staging-awards-row').count(),20);
  assert.equal(await page.locator('[aria-label="Awards and nominations"] button').count(),0);
  const awardsWindow=await page.locator('.staging-awards-table').evaluate(e=>({height:e.clientHeight,total:e.scrollHeight,expected:e.querySelector('.staging-awards-header').getBoundingClientRect().height+[...e.querySelectorAll('.staging-awards-row')].slice(0,5).reduce((n,row)=>n+row.getBoundingClientRect().height,0)}));assert(awardsWindow.total>awardsWindow.height);assert(Math.abs(awardsWindow.height-awardsWindow.expected)<2);
  await page.locator('.staging-awards-table').focus();await page.keyboard.press('End');await page.waitForTimeout(150);assert(await page.locator('.staging-awards-table').evaluate(e=>e.scrollTop>0));
  const grossWindow=await page.locator('.staging-revenue-scroll').evaluate(e=>({height:e.clientHeight,total:e.scrollHeight,width:e.clientWidth,scrollWidth:e.scrollWidth,expected:e.querySelector('thead').getBoundingClientRect().height+[...e.querySelectorAll('tbody tr')].slice(0,5).reduce((n,row)=>n+row.getBoundingClientRect().height,0),sticky:getComputedStyle(e.querySelector('thead')).position}));assert(Math.abs(grossWindow.height-grossWindow.expected)<2);assert(grossWindow.total>grossWindow.height);assert(grossWindow.scrollWidth<=grossWindow.width);assert.equal(grossWindow.sticky,'sticky');await page.locator('.staging-revenue-scroll').focus();await page.keyboard.press('End');await page.waitForTimeout(150);assert(await page.locator('.staging-revenue-scroll').evaluate(e=>e.scrollTop>0));
  const awardsInsets=await page.locator('.staging-awards-header,.staging-awards-row').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().height).map(e=>({left:getComputedStyle(e).paddingLeft,right:getComputedStyle(e).paddingRight,numeric:getComputedStyle(e.lastElementChild).textAlign})));awardsInsets.forEach(e=>{assert.equal(e.left,'16px');assert.equal(e.right,'16px');assert.equal(e.numeric,'right');});assert(await page.locator('.staging-awards-table').evaluate(e=>e.scrollWidth<=e.clientWidth));
  const providers=await page.locator('.staging-platform').evaluateAll(es=>es.map(e=>({top:getComputedStyle(e).paddingTop,bottom:getComputedStyle(e).paddingBottom,paragraph:[...e.querySelectorAll('p')].map(p=>({top:getComputedStyle(p).marginTop,bottom:getComputedStyle(p).marginBottom}))})));providers.forEach(e=>{assert.equal(e.top,e.bottom);e.paragraph.forEach(p=>{assert.equal(p.top,'4px');assert.equal(p.bottom,'0px');});});
  const tracks=await page.locator('.staging-score-track').evaluateAll(es=>es.map(e=>getComputedStyle(e).backgroundColor));assert(tracks.every(c=>c==='rgba(0, 0, 0, 0)'));
  const grossGroups=await page.locator('.staging-gross-film').evaluateAll(es=>es.map(e=>({minimum:getComputedStyle(e.querySelector('a')).minHeight,gap:e.querySelector('p').getBoundingClientRect().top-e.querySelector('a').getBoundingClientRect().bottom,text:e.querySelector('p').textContent})));grossGroups.forEach(g=>{assert.equal(g.minimum,'0px');assert(Math.abs(g.gap-4)<1);assert(/^\$[\d,]+M USD$/.test(g.text));});
  if(width>=720){
    await page.getByRole('button',{name:'Collapse navigation',exact:true}).click();
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    const collapsed=await page.locator('.staging-awards-table').evaluate(e=>({height:e.clientHeight,expected:e.querySelector('.staging-awards-header').getBoundingClientRect().height+[...e.querySelectorAll('.staging-awards-row')].slice(0,5).reduce((n,row)=>n+row.getBoundingClientRect().height,0)}));assert(Math.abs(collapsed.height-collapsed.expected)<2);
    await page.screenshot({path:output+'/staging-collapsed-'+width+'.png',fullPage:true});
    await page.getByRole('button',{name:'Expand navigation',exact:true}).click();
  }
  await page.getByRole('tab',{name:'Tastes',exact:true}).click();
  const stars=page.locator('[aria-label="Shared stars"]');assert.equal(await stars.locator('tbody tr:not(.metrics-table-pages)').count(),20);await stars.getByRole('button',{name:'Next',exact:true}).click();assert.equal(await stars.locator('tbody tr:not(.metrics-table-pages)').count(),3);await stars.getByRole('button',{name:'Previous',exact:true}).click();
  assert.equal(await page.locator('.staging-report').count(),3);assert.equal(await page.locator('.staging-matrix td[aria-label]').count(),50);
  const genreCells=await page.locator('[aria-label="Genre taste overlap"] td[data-diagonal=false]').evaluateAll(es=>es.map(e=>getComputedStyle(e).backgroundColor));assert.equal(new Set(genreCells).size,10);
  const comparisons=await page.locator('[aria-label="Genre taste overlap"] .staging-comparison-group').evaluateAll(es=>es.map((e,a)=>[...e.querySelectorAll('li')].map((line,i)=>{const b=i>=a?i+1:i,cell=e.closest('section').querySelectorAll('tbody tr')[a].querySelectorAll('td')[b];return {text:line.lastElementChild.textContent,desktop:cell.textContent,colour:getComputedStyle(line.lastElementChild).color,palette:getComputedStyle(cell).backgroundColor};})).flat());comparisons.forEach(e=>{assert.equal(e.text,e.desktop);assert.equal(e.colour,e.palette);});
  const subtitles=await page.locator('.staging-report > p.meta:first-of-type').allTextContents();subtitles.forEach(text=>assert(text.length<150));
  assert.equal(await page.locator('.metrics-genre-combinations').count(),0);
  const matrices=await page.locator('.staging-matrix-scroll').evaluateAll(es=>es.map(e=>({width:e.clientWidth,total:e.scrollWidth})));
  const contentWidth=await page.locator('.metrics-content').evaluate(e=>e.clientWidth);
  assert.equal(await page.locator('.staging-mobile-comparisons').first().isVisible(),contentWidth<720);
  assert.equal(await page.locator('.staging-matrix-scroll').first().isVisible(),contentWidth>=720);
  const accessible=await page.locator('[aria-label="Genre taste overlap"]').ariaSnapshot();assert.equal(accessible.includes('participant comparisons'),contentWidth<720);assert.equal(accessible.includes('scroll horizontally'),contentWidth>=720);
  if(width>=720){await page.getByRole('button',{name:'Collapse navigation',exact:true}).click();const available=await page.locator('.metrics-content').evaluate(e=>e.clientWidth);assert.equal(await page.locator('.staging-mobile-comparisons').first().isVisible(),available<720);assert.equal(await page.locator('.staging-matrix-scroll').first().isVisible(),available>=720);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.getByRole('button',{name:'Expand navigation',exact:true}).click();}
  assert.equal(await page.locator('.staging-comparison-group').count(),10);assert.equal(await page.locator('.staging-comparison-group li').count(),40);
  if(contentWidth<720){assert.equal(await page.locator('.staging-matrix-scroll:visible').count(),0);const lines=await page.locator('.staging-comparison-group li').evaluateAll(es=>es.map(e=>({width:e.clientWidth,total:e.scrollWidth})));assert(lines.every(e=>e.total<=e.width+1));}

  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.evaluate(()=>window.enrichmentReads),1);
  await page.screenshot({path:output+'/tastes-'+width+'.png',fullPage:true});await page.locator(contentWidth<720?'.staging-mobile-comparisons':'.staging-matrix-scroll').first().screenshot({path:output+'/matrix-'+width+'.png'});

  assert.equal(await stars.locator('.metrics-table-pages td').getAttribute('colspan'),'6');assert.deepEqual(await stars.locator('thead th').allTextContents(),['Actor','Sean','Troy','Matt','Jess','Total']);
  await page.locator('.metrics-filters button').nth(1).click();assert.equal(await page.locator('.staging-matrix td[aria-label]').count(),50);assert(await page.locator('[data-emphasis=true]').count()>0);
  await page.getByRole('tab',{name:'Breakdowns',exact:true}).click();
  await page.screenshot({path:output+'/breakdowns-'+width+'.png',fullPage:true});
  await page.locator('.metrics-filters button').nth(1).click();assert.deepEqual(await page.locator('[aria-label^="Shared"]').evaluateAll(es=>es.map(e=>e.getAttribute('aria-label'))),axes);assert.equal(await page.locator('.staging-chart-row').count(),3);assert.equal(await page.locator('.staging-matrix').count(),0);
  const disclosures=page.locator('.staging-collection');assert.equal(await disclosures.locator('summary a').count(),0);assert.equal(await page.locator('.staging-collection[open]').count(),0);
  await disclosures.nth(0).locator('summary').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('.staging-collection[open]').count(),1);await disclosures.nth(1).locator('summary').click();assert.equal(await page.locator('.staging-collection[open]').count(),2);
  if(width===390){await disclosures.nth(1).screenshot({path:output+'/collection-expanded-390.png'});await page.locator('.staging-awards-table').screenshot({path:output+'/awards-390.png'});}
  const missingInset=await page.locator('.staging-missing-films').evaluate(e=>({label:e.firstElementChild.getBoundingClientRect().left,title:e.children[1].getBoundingClientRect().left,padding:getComputedStyle(e.children[1]).paddingLeft}));assert.equal(missingInset.padding,'16px');assert.equal(missingInset.label,missingInset.title);
  const disclosureGeometry=await disclosures.evaluateAll(es=>es.map(e=>({target:e.querySelector('summary').getBoundingClientRect().height,margin:getComputedStyle(e.querySelector('h3')).marginTop})));disclosureGeometry.forEach(e=>{assert(e.target>=44);assert.equal(e.margin,'0px');});
  const denseLists=await page.locator('.metrics-metadata-films').evaluateAll(es=>es.map(e=>({font:getComputedStyle(e).fontSize,gap:getComputedStyle(e).rowGap,margin:getComputedStyle(e).marginTop,padding:parseFloat(getComputedStyle(e).paddingLeft),rows:[...e.children].map(n=>({top:n.getBoundingClientRect().top,bottom:n.getBoundingClientRect().bottom,margin:getComputedStyle(n).marginTop,padding:getComputedStyle(n).paddingTop,linkMinimum:getComputedStyle(n.querySelector('a')).minHeight})),left:e.getBoundingClientRect().left,first:e.firstElementChild.getBoundingClientRect().left})));
  denseLists.forEach(list=>{assert.equal(list.font,'13px');assert.equal(list.gap,'0px');assert.equal(list.margin,'0px');assert(list.first>list.left);list.rows.forEach((row,i)=>{assert.equal(row.margin,'0px');assert.equal(row.padding,'0px');assert.equal(row.linkMinimum,'0px');if(i)assert(Math.abs(row.top-list.rows[i-1].bottom)<1);});});
  const gross=await page.locator('.staging-revenue-table tbody tr').evaluateAll(es=>es.map(e=>({genre:getComputedStyle(e.firstElementChild).fontSize,title:getComputedStyle(e.querySelector('.movie-title')).fontSize})));gross.forEach(g=>assert.equal(g.genre,g.title));
  const classifications=await page.locator('.staging-classification h3').evaluateAll(es=>es.map(e=>({label:e.textContent,height:e.getBoundingClientRect().height,line:parseFloat(getComputedStyle(e).lineHeight),width:e.getBoundingClientRect().width,total:e.scrollWidth})));classifications.forEach(c=>{assert(Math.abs(c.height-c.line)<1);assert(c.total<=c.width+1);});
  assert.equal(await page.locator('[aria-label="Franchise / collection completed"] .metrics-metadata-films a').count(),2);assert.equal(await page.locator('[aria-label="Incomplete collections"] .metrics-metadata-films a').count(),2);assert((await page.locator('[aria-label="Incomplete collections"]').textContent()).includes('2 of 3 films'));

  await page.getByRole('tab',{name:'Records',exact:true}).click();assert.equal(await page.locator('.metrics-film-extreme').count(),10);assert.equal(await page.locator('.metrics-reception-record').count(),2);assert.equal(await page.locator('.metrics-viewed-record').count(),2);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:output+'/records-'+width+'.png',fullPage:true});
  await page.getByRole('tab',{name:'Top 5',exact:true}).click();assert.equal(await page.locator('.metrics-genre-combinations').count(),1);assert.equal(await page.locator('.staging-report').count(),3);assert.equal(await page.locator('.metrics-genre-combinations > .meta').textContent(),'Unique genre subsets of two or more genres.');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  const partnership=page.locator('[aria-label="Creative partnerships"] select');assert.deepEqual(await partnership.locator('option').allTextContents(),['Writer','Composer','Cinematographer','Editor']);for(const role of ['Composer','Cinematographer','Editor']){await partnership.selectOption(role);assert.equal(await page.locator('[aria-label="Creative partnerships"] section').count(),1);}await page.getByRole('tab',{name:'Tastes',exact:true}).click();await page.getByRole('tab',{name:'Top 5',exact:true}).click();assert.equal(await partnership.inputValue(),'Editor');
  const rowStructure=await page.locator('.staging-discoveries li:not(.metrics-result-pages)').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect(),rank=e.querySelector('.staging-discovery-rank').getBoundingClientRect(),poster=e.querySelector('.poster').getBoundingClientRect(),text=e.querySelector('.staging-discovery-text').getBoundingClientRect(),index=e.querySelector('.staging-discovery-index').getBoundingClientRect();return {rank:rank.left,poster:poster.left,posterHeight:poster.height,posterLinkHeight:e.querySelector('li > a').getBoundingClientRect().height,text:text.left,right:r.right,indexRight:index.right,indexTop:index.top,top:r.top};}));
  rowStructure.forEach(r=>{assert(r.rank<r.poster&&r.poster<r.text);assert.equal(r.posterHeight,96);assert.equal(r.posterLinkHeight,96);assert(Math.abs(r.indexRight-r.right)<1);assert(Math.abs(r.indexTop-r.top-16)<1);});
  const metadata=await page.locator('.staging-discovery-text .movie-copy').evaluateAll(es=>es.map(e=>[...e.children].map(n=>n.textContent)));
  metadata.forEach(lines=>{assert(lines[1].startsWith('Audience'));assert(lines[2].includes(' min '));assert(lines[2].endsWith('M'));assert(lines[3].includes('Director'));});
  await page.screenshot({path:output+'/top-five-'+width+'.png',fullPage:true});
  assert.deepEqual(await page.getByRole('tab').allTextContents(),['Top 5','Tastes','Breakdowns','Records']);
  for(const label of Object.keys(inventory)) {
    await page.getByRole('tab',{name:label,exact:true}).click();
    // Identity filtering retains report count/order; reset the score/vote selectors remain at their defaults.
    assert.deepEqual(await page.locator('.metrics-panel h2,.metrics-panel h3').evaluateAll(es=>es.filter(e=>e.textContent!=='Records'&&(e.tagName==='H2'||!e.closest('.staging-report'))).map(e=>e.textContent)),inventory[label]);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    if(width>=720) {
      await page.getByRole('button',{name:'Collapse navigation',exact:true}).click();
      assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
      await page.screenshot({path:output+'/'+label.toLowerCase().replaceAll(' ','-')+'-collapsed-'+width+'.png',fullPage:true});
      await page.getByRole('button',{name:'Expand navigation',exact:true}).click();
    }
  }
  assert.equal(await page.evaluate(()=>window.enrichmentReads),1);
  samples.push({width,cycle,matrices,axes,geometry,bars,rowStructure,denseLists,gross,classifications});
 }
 assert.deepEqual(errors,[]);fs.writeFileSync(output+'/measurements.json',JSON.stringify({samples,errors},null,2));console.log('Four Metrics categories: all 15 relocated reports, approved inventories, five-cycle window with older cycles, stable axes, accessible contained matrices, cached reads and no overflow passed at 320/390/720/951/1440px.');
} finally {await browser.close();}
