// Local rendered style contract. All API functions are synthetic and every external request is blocked.
import fs from 'node:fs';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.BOOKCLUB_PLAYWRIGHT_MODULE || '../.verification/node_modules/playwright/index.mjs');
const phase=process.env.BOOKCLUB_STYLE_PHASE || 'after';
const output='.verification/style-unification/'+phase;
fs.mkdirSync(output,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.BOOKCLUB_BROWSER_PATH || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
const page=await browser.newPage(),errors=[],blocked=[],samples=[];
page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',r=>{const u=new URL(r.request().url());if(['localhost','127.0.0.1'].includes(u.hostname))return r.fallback();blocked.push(u.hostname);return r.abort();});
await page.route('**/api/**',r=>{errors.push('Unmocked API request');return r.abort();});await page.route('**/__dev/**',r=>r.abort());
await page.route(/\/frontend\/api\.ts(?:\?.*)?$/,r=>r.fulfill({contentType:'text/javascript',body:"export const api=globalThis.__auditApi ??= {};export class ApiClientError extends Error {}export const hasSession=()=>true;export const setUnauthorizedHandler=()=>{};export const setDevMember=()=>{};export const clearSession=()=>{};export const storeSession=()=>{};"}));
const source=await(await fetch('http://localhost:4173/frontend/main.tsx')).text(),reactUrl=source.match(/from "([^"\n]+\/react\.js[^"\n]*)"/)[1],domUrl=source.match(/from "([^"\n]+\/react-dom_client\.js[^"\n]*)"/)[1];
await page.route(/\/frontend\/main\.tsx(?:\?.*)?$/,r=>r.fulfill({contentType:'text/javascript',body:`
import React from '${reactUrl}';import ReactDOM from '${domUrl}';import '/style.css';import '/frontend/app.css';
import '/node_modules/@fontsource/lexend-deca/300.css';import '/node_modules/@fontsource/lexend-deca/400.css';import '/node_modules/@fontsource/lexend-deca/500.css';import '/node_modules/@fontsource/lexend-deca/600.css';import '/node_modules/@fontsource/lexend-deca/700.css';import '/node_modules/@fontsource/lexend-deca/800.css';
import {App} from '/frontend/App.tsx';import {SignInScreen} from '/frontend/SignInScreen.tsx';import {AvatarScreen} from '/frontend/AvatarScreen.tsx';import {metricsFixture} from '/tests/metrics-fixture.ts';import {api} from '/frontend/api.ts';import {rankMovie} from '/shared/ranking.ts';import {metricsEnrichmentFixture} from '/tests/metrics-enrichment-fixture.ts';import {HistoryEvidence} from '/frontend/HistoryEvidence.tsx';import {LoadingView,Failure,Action,SourceScores} from '/frontend/components.tsx';import {EnrichedMetrics} from '/frontend/EnrichedMetrics.tsx';
const catalog=metricsFixture();catalog.members.forEach((m,i)=>m.avatar=i+1);catalog.cycles=[{id:'cycle1',ordinal:1,rough_date:'2026-01-01',title:null}];catalog.sessions.forEach((s,i)=>{s.cycle_id='cycle1';s.cycle_slot=i%5+1;});
const candidates=[0,1,2].map(i=>({...catalog.movies[i],id:'candidate'+i,title:i===0?'A very long candidate title that tests wrapping beside row controls and narrow score presentations':'Candidate '+i,overview:'Synthetic overview with enough words to check the collapsed description. '.repeat(12),classic:true,seen:i===1?[]:catalog.members.map(m=>({member_id:m.id,seen:i===2?1:0,updated_at:''})),external_ids:[{provider:'tmdb',external_id:String(i+100)},{provider:'imdb',external_id:'tt000000'+i}],ranking:null,appearances:[]}));candidates[0].scores=[['imdb','rating'],['letterboxd','rating'],['metacritic','critic'],['metacritic','user'],['rottentomatoes','audience'],['rottentomatoes','critic'],['tmdb','rating'],['trakt','rating'],['rogerebert','rating']].map(([provider,metric])=>({provider,metric,raw_value:80,raw_scale:100,normalized_value:80,vote_count:123456,fetched_at:'2026-01-01'}));candidates.forEach(m=>m.ranking=rankMovie(m.scores,m.seen,catalog.members));catalog.movies.push(...candidates);window.auditCatalog=catalog;
api.health=async()=>({status:'ok',environment:'local',authenticationRequired:false,demo:true});api.me=async()=>({viewer:{...catalog.members[1],role:'admin'}});api.catalog=async()=>catalog;api.rotation=async()=>({id:1,cycle_id:'cycle1',nominal_slot:2,version:0,updated_at:''});api.builders=async()=>[{id:'set1',owner_member_id:'m2',title:'Synthetic private set',notes:'Synthetic saved notes',movie_ids:['a','b'],created_at:'2026-01-01',updated_at:'2026-01-01',revision:1}];
api.detail=async id=>({...catalog.movies.find(m=>m.id===id),appearances:[]});api.preview=async id=>({...catalog.movies[0],id,tmdb_id:Number(id)});api.search=async()=>({local:catalog.movies.map(m=>({...m,tmdbId:null,poster:null})),external:[],lookup:{available:true,message:null}});api.historyAudit=async()=>[];api.scoreMaintenanceStatus=async()=>({candidateIds:candidates.map(m=>m.id),eligibleDimensions:12345,unavailableDimensions:2345,unavailableFilms:1234});api.metricsEnrichment=async()=>metricsEnrichmentFixture();api.avatars=async()=>[1,2,3,4];
api.saveBuilder=async(body,id)=>({...body,id:id||'synthetic-set',owner_member_id:'m2',created_at:'2026-01-01',updated_at:'2026-01-01',revision:2});
api.maintainMovies=async(mode,ids)=>new Promise(resolve=>{window.finishBatch=()=>resolve({results:ids.map(id=>({movie:{...catalog.movies.find(m=>m.id===id),appearances:[]},providers:[{provider:'omdb',status:'success',count:1234,message:'Synthetic saved batch'}]}))});});
api.enrichMetadataSelected=async ids=>new Promise(resolve=>{window.finishBatch=()=>resolve({results:ids.map(movieId=>({movieId,provider:'tmdb',status:'success',message:'Synthetic saved batch'}))});});
api.enrichProvider=async(provider,ids)=>new Promise(resolve=>{window.finishBatch=()=>resolve({results:ids.map(movieId=>({movieId,status:'updated',message:'Synthetic saved batch'})),canonicalChanged:false});});
const mode=new URL(location.href).searchParams.get('audit');if(mode==='counts'){for(let i=0;i<1234;i++){const movie={...candidates[0],id:'count'+i,scores:[],seen:[]};movie.ranking=rankMovie(movie.scores,movie.seen,catalog.members);catalog.movies.push(movie);}}if(mode==='operations'){for(let i=0;i<24;i++)catalog.movies.push({...candidates[0],id:'operation'+i});api.scoreMaintenanceStatus=async()=>({candidateIds:catalog.movies.map(m=>m.id),eligibleDimensions:12345,unavailableDimensions:2345,unavailableFilms:1234});for(const key of ['bookclub.omdb-metadata.v1','bookclub.tmdb-enrichment.v1','bookclub.mdblist-enrichment.v1'])localStorage.setItem(key,JSON.stringify({version:1,remainingIds:catalog.movies.filter(m=>m.external_ids.length).map(m=>m.id),completed:12345}));}const node=mode==='loading'?React.createElement(LoadingView):mode==='failure'?React.createElement(Failure,{message:'Synthetic recoverable failure',retry:()=>{}}):mode==='evidence'?React.createElement(HistoryEvidence,{catalog,json:JSON.stringify({before:{event_date:'2026-01-01',movie_ids:['a','b'],kind:'hosted',host_member_id:'m2'},after:{event_date:'2026-01-02',movie_ids:['a'],kind:'classics'},turn_before:{nominal_slot:2,cycle_id:'cycle1'}})}):mode==='metrics-error'?React.createElement(EnrichedMetrics,{category:'fingerprints',catalog,all:[],rows:[],filter:{kind:'all'},data:{movies:{}},status:'error',retry:()=>{}}):mode==='signin'?React.createElement(SignInScreen,{configured:false,error:'Synthetic sign-in error',busy:false,onCredential:async()=>{},onRetry:()=>{},onLocalLogin:async()=>{}}):mode==='avatar'?React.createElement(AvatarScreen,{viewer:catalog.members[1],onClaimed:()=>{},onLogout:()=>{},externalError:'Synthetic claim collision'}):React.createElement(App);ReactDOM.createRoot(document.getElementById('root')).render(node);
`}));
async function capture(area,state,width){
 await page.waitForTimeout(180);await page.evaluate(()=>document.fonts.ready);
 const measurements=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,controls:[...document.querySelectorAll('button,.button,summary,input:not([type=radio]):not([type=checkbox]),select')].filter(e=>e.getClientRects().length).map(e=>{const c=getComputedStyle(e),r=e.getBoundingClientRect();return {label:e.getAttribute('aria-label')||e.textContent.trim(),classes:e.className,width:r.width,height:r.height,font:c.fontSize,weight:c.fontWeight,gap:c.gap,padding:c.padding,focus:c.outlineStyle};})}));
 if(phase==='after'){
  assert.equal(measurements.overflow,false,area+' '+state+' at '+width+'px overflows');
  for(const c of measurements.controls){if(c.classes?.includes('button')||c.classes?.includes('tab-control')){assert(c.height>=44,area+' undersized '+c.label);assert.equal(c.font,'15px',area+' button role '+c.label);}}
  const clipped=await page.locator('.button').evaluateAll(nodes=>nodes.filter(e=>e.getClientRects().length&&e.scrollWidth>e.clientWidth+1).map(e=>e.textContent));assert.deepEqual(clipped,[],area+' clipped action label');
  const account=page.locator('.account-menu-trigger');if(await account.count()){const target=await account.boundingBox();assert(target.width>=44&&target.height>=44,'Account target');}
  const overlaps=await page.locator('.classic-remove').evaluateAll(nodes=>nodes.filter(e=>{const a=e.getBoundingClientRect(),b=e.parentElement.querySelector('.movie-link').getBoundingClientRect();return a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top;}).length);
  assert.equal(overlaps,0,'Classics remove overlaps film link');
 }
 const name=(area+'-'+state).toLowerCase().replace(/[^a-z0-9]+/g,'-');
 await page.screenshot({path:output+'/'+width+'-'+name+'.png',fullPage:true});
 samples.push({area,state,width,...measurements});
}
async function verifyControlStates(){
 const stateResults=[];
for (const width of [320,390,720,951,1440]) for (const [route,selector] of [['home','.turn-actions .button'],['classics','.classics-filters .tab-control,.classic-remove'],['seen','.answer-actions .button'],['admin','.button']]) {
 await page.setViewportSize({width,height:900});await page.goto('http://localhost:4173/#/'+route);await page.waitForTimeout(350);
 if(route==='classics'){await page.goto('http://localhost:4173/?audit=counts#/classics');await page.waitForTimeout(350);const capped=page.getByRole('button',{name:/^Unranked: 1,23[4-7] films$/});await capped.waitFor();assert.equal(await capped.locator('.count-indicator').innerText(),'99+');await capture('Classics','full accessible capped count',width);}
 const nodes=await page.locator(selector).all();assert(nodes.length,route+' controls missing');
 for (const node of nodes) {
  if(!await node.isVisible())continue;
  if(!await node.isEnabled()){assert.equal(await node.evaluate(e=>e.disabled),true);continue;}
  await page.keyboard.press('Tab');await node.focus();
  const focused=await node.evaluate(e=>{const c=getComputedStyle(e);return {visible:e.matches(':focus-visible'),outline:c.outlineStyle,width:parseFloat(c.outlineWidth)};});
  assert(focused.visible&&focused.outline!=='none'&&focused.width>=2,route+' focus');
  const normal=await node.evaluate(e=>{const c=getComputedStyle(e),r=e.getBoundingClientRect();return {width:r.width,height:r.height,color:c.color,bg:c.backgroundColor,padding:c.padding};});
  await node.hover();await page.waitForTimeout(190);
  const hovered=await node.evaluate(e=>{const rgb=x=>{const n=x.match(/[\d.]+/g).map(Number);return [n[0],n[1],n[2],n[3]??1];};let bg=[34,34,34];const chain=[];for(let p=e;p;p=p.parentElement)chain.unshift(p);for(const p of chain){const a=rgb(getComputedStyle(p).backgroundColor);bg=bg.map((v,i)=>a[i]*a[3]+v*(1-a[3]));}const c=getComputedStyle(e),fg=rgb(c.color),lum=a=>a.slice(0,3).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}).reduce((v,n,i)=>v+n*[.2126,.7152,.0722][i],0);const a=lum(fg),b=lum(bg),r=e.getBoundingClientRect();return {color:c.color,bg:c.backgroundColor,contrast:(Math.max(a,b)+.05)/(Math.min(a,b)+.05),width:r.width,height:r.height,padding:c.padding,selected:e.getAttribute('aria-pressed'),underline:getComputedStyle(e,'::after').height};});
  assert(hovered.contrast>=4.5,route+' contrast '+hovered.contrast);assert.equal(hovered.height,normal.height);assert.equal(hovered.width,normal.width);assert.equal(hovered.padding,normal.padding);
  if(hovered.selected==='true'&&await node.evaluate(e=>e.classList.contains('tab-control')))assert.equal(hovered.underline,'3px');
  stateResults.push({width,route,label:await node.innerText(),focused,hovered});
 }
 await page.screenshot({path:output+'/'+width+'-'+route+'-hover-focus.png',fullPage:false});
}
assert.deepEqual(errors,[]);fs.writeFileSync(output+'/control-states.json',JSON.stringify(stateResults,null,2));console.log('Passed '+stateResults.length+' enabled hover/focus/contrast cases plus disabled controls at all five widths.');
}
try{if(process.env.BOOKCLUB_STYLE_CONTROLS_ONLY!=='1'){for(const width of [320,390,720,951,1440]){await page.setViewportSize({width,height:900});for(const [area,hash]of [['Home','home'],['History','history'],['Builder','builder'],['Classics','classics'],['Seen','seen'],['Metrics','metrics'],['Admin','admin'],['Event','event'],['Film Detail','movie/candidate0'],['External Preview','preview/tmdb/100'],['Not found','unknown']]){await page.goto('http://localhost:4173/#/'+hash);await page.waitForTimeout(300);await capture(area,'initial',width);if(phase==='after'&&width>=720&&area!=='Home'){const expand=page.getByRole('button',{name:'Expand navigation',exact:true});if(await expand.count()){await expand.click();await capture(area,'expanded navigation',width);await page.getByRole('button',{name:'Collapse navigation',exact:true}).click();}}
if(area==='Classics'){for(const name of ['Ranked','Unranked','Seen']){const button=page.getByRole('button',{name:new RegExp('^'+name+':')});if(await button.count()){await button.click();await capture(area,name+' tab',width);}}const remove=page.locator('.classic-remove').first();if(await remove.count()){await remove.click();await capture('Remove Classic dialog','open',width);await page.keyboard.press('Escape');}await page.getByRole('button',{name:'Add Classic',exact:true}).click();await capture('Add Classic dialog','open',width);await page.keyboard.press('Escape');}
if(area==='Metrics'){for(const name of ['Fingerprints','General','Averages','Diversity','Standalone','Extremes']){await page.getByRole('tab',{name,exact:true}).click();await page.waitForTimeout(100);await capture('Metrics',name+' tab',width);}}
if(area==='Builder'){await page.getByRole('button',{name:'Open set',exact:true}).first().click();await capture(area,'editor populated',width);await page.getByLabel('Search saved films & TMDB').fill('film');await page.getByRole('button',{name:'Search',exact:true}).click();await page.waitForTimeout(100);await capture(area,'search results',width);}
if(area==='History'&&phase==='after'){await page.locator('.history-event [data-variant="danger"]').first().click();await capture('History deletion dialog','open',width);await page.keyboard.press('Escape');}
if(area==='Seen'){const toggle=page.getByRole('button',{name:'More',exact:true});if(await toggle.count()){await toggle.click();await capture(area,'expanded overview',width);}}
if(area==='Film Detail'){const help=page.getByRole('button',{name:'Explain score abbreviations',exact:true});if(await help.count()){await help.click();await capture('Score glossary dialog','open',width);await page.keyboard.press('Escape');}}
if(area==='Home'){await page.locator('.account-menu-trigger').click();await capture('Account dropdown','open',width);await page.keyboard.press('Escape');if(phase==='after'){await page.getByRole('button',{name:'Use from Builder',exact:true}).click();await capture('Builder set picker','open',width);await page.keyboard.press('Escape');}await page.locator('.data-sources summary').click();await capture('Attribution','expanded',width);if(width>=720){await page.getByRole('button',{name:'Collapse navigation',exact:true}).click();await page.locator('.desktop-navigation nav a').first().hover();await capture('Navigation','collapsed hovered tooltip',width);}}
if(area==='Admin'){await page.locator('.developer-tools summary').click();await capture('Developer tools','expanded',width);for(const e of await page.locator('.maintenance-details summary').all())await e.click();await capture(area,'operation disclosures expanded',width);if(phase==='after'){await page.getByRole('button',{name:'Refresh Dev DB from Production',exact:true}).click();await capture('Developer tools','confirmation only',width);await page.getByRole('button',{name:'Cancel',exact:true}).click();}}
}for(const mode of ['signin','avatar','loading','failure','evidence','metrics-error']){await page.goto('http://localhost:4173/?audit='+mode);await page.waitForTimeout(300);if(mode==='evidence')await page.getByText('Change evidence',{exact:true}).click();await capture(mode,'populated-error',width);}console.log('runtime width '+width);}
if(phase==='after') {
 const operations=['Populate Missing Scores','Refresh Scores','Refresh OMDb Metadata','Fill Missing TMDB Metadata and Artwork','Refresh TMDB Enrichment','Refresh MDBList Enrichment'];
 for(const width of [320,390,720,951,1440]) for(const operation of operations) {
  await page.setViewportSize({width,height:900});await page.goto('http://localhost:4173/?audit=operations#/admin');
  const card=page.locator('section',{has:page.getByRole('heading',{name:operation,exact:true})});await card.waitFor();
  await card.locator('.button-set .button').first().click();await page.waitForFunction(()=>typeof window.finishBatch==='function');
  const stop=card.getByRole('button',{name:'Stop after this batch',exact:true});await stop.focus();
  assert(await stop.evaluate(e=>e===document.activeElement));await capture('Admin '+operation,'focused running',width);
  await stop.click();await page.evaluate(()=>window.finishBatch());await stop.waitFor({state:'detached'});
  await capture('Admin '+operation,'stopped progress resume',width);
  const discard=card.getByRole('button',{name:/^Discard /});if(await discard.count()){await discard.click();await capture('Admin '+operation,'discarded',width);}
 }
}
}
if(phase==='after')await verifyControlStates();
if(process.env.BOOKCLUB_STYLE_CONTROLS_ONLY!=='1')fs.writeFileSync(output+'/results.json',JSON.stringify({samples,errors,blocked:[...new Set(blocked)]},null,2));console.log(JSON.stringify({samples:samples.length,errors,blocked:[...new Set(blocked)]}));assert.deepEqual(errors,[]);}catch(error){console.error({errors,area:samples.at(-1)?.area});throw error;}finally{await browser.close();}
