import { ratingDimensions, type RatingDimensionKey } from './rating-dimensions';
import { isLiveScore,scoreValue } from './ranking';
import type { Score } from './types';

export const maintainedScoreKeys=Object.keys(ratingDimensions) as RatingDimensionKey[];
export const scoreProviderKeys={mdblist:maintainedScoreKeys,omdb:['imdb:rating','rottentomatoes:critic','metacritic:critic'],tmdb:['tmdb:rating']} satisfies Record<string,readonly string[]>;
export function missingMaintainedScores(scores:Score[]){const present=new Set(scores.filter(s=>isLiveScore(s)&&scoreValue(s)!==null).map(s=>`${s.provider}:${s.metric}`));return maintainedScoreKeys.filter(key=>!present.has(key));}
export interface CollectedField {id:string;label:string;source:string;store:string;kind:'text'|'number'|'family';optional:boolean;positive?:boolean;group:string}
const field=(id:string,label:string,source:string,store:string,kind:CollectedField['kind']='text',positive=false,optional=true):CollectedField=>({id,label,source,store,kind,optional,group:label,...(positive?{positive:true}:{})});
const meta='movie_provider_metadata',canonical='movies',relations='movie_provider_';
export const maintenanceContract={
  scores:{name:'scores',providers:['mdblist','omdb','tmdb'],scope:'Distinct Classics, active History and currently saved Builder films and AI predictions.',fields:maintainedScoreKeys.map(key=>field(key,ratingDimensions[key].fullLabel,key,'source_scores','number')),success:'Nine maintained ratings are separate from the six Watch Order requirements. Only capable providers are checked; genuine observations and conclusive absences are retained.'},
  'omdb-metadata':{name:'OMDb metadata',providers:['omdb'],scope:'All catalogue films with a valid IMDb identity.',fields:[field('title','Provider title','Title',meta),field('year','Release year','Year',canonical,'number'),field('runtime','Runtime','Runtime',canonical,'number'),field('director','Director','Director',canonical),field('genres','Genres','Genre','movie_genres','family')],success:'Coverage records OMDb title evidence independently of the displayed title. Available metadata is saved with its successful check.'},
  'tmdb-metadata':{name:'TMDB metadata and artwork',providers:['tmdb'],scope:'All catalogue films with a valid TMDB identity.',fields:[field('title','Provider title','title',meta,'text',false,false),field('original_title','Original title','original_title',canonical),field('release','Release date and year','release_date',canonical),field('runtime','Runtime','runtime',canonical,'number'),field('overview','Overview','overview',canonical),field('director','Director','credits',canonical),field('genres','Genres','genres','movie_genres','family'),field('poster','Poster','poster_path','movie_assets'),field('backdrop','Backdrop','backdrop_path','movie_assets')],success:'Title evidence belongs to TMDB. A successfully absent poster or backdrop is complete; Populate preserves populated canonical values.'},
  'tmdb-enrichment':{name:'TMDB enrichment',providers:['tmdb'],scope:'All catalogue films with a valid TMDB identity.',fields:[field('title','Provider title','title',meta,'text',false,false),field('original_language','Original language','original_language',meta),field('budget','Budget','budget',meta,'number',true),field('revenue','Revenue','revenue',meta,'number',true),field('popularity','Popularity','popularity',meta,'number'),field('tagline','Tagline','tagline',meta),...['countries','languages','companies','credits','content_ratings','keywords','watch_offers'].map((id,i)=>field(id,['Production countries','Spoken languages','Production companies','Top-15 cast and exact crew roles','US/AU certifications','Keywords','Australian watch availability'][i],['production_countries','spoken_languages','production_companies','credits','release_dates','keywords','watch/providers'][i],relations+id,'family'))],success:'Validated empty relationship sets are complete. Zero financial values are checked but unavailable as positive amounts. Missing or malformed scalar evidence is kept distinct from checked absence.'},
  'mdblist-enrichment':{name:'MDBList enrichment',providers:['mdblist'],scope:'All identified catalogue films; IMDb is preferred, otherwise TMDB.',fields:[field('title','Provider title','title',meta),field('runtime','Runtime','runtime',meta,'number'),field('keywords','Keywords','keywords',relations+'keywords','family'),field('identities','Safe external identity claims','ids',relations+'identity_claims','family')],success:'Empty keywords and no new external IDs can be complete. Identity claims preserve existing ownership; regionless watch data is excluded.'},
  'tmdb-collections':{name:'TMDB collections',providers:['tmdb'],scope:'All catalogue films with a valid TMDB identity.',fields:[field('collection_id','Collection ID','belongs_to_collection','movie_provider_collections','number'),field('collection_name','Collection name','belongs_to_collection','movie_provider_collections')],success:'Explicit collection-free evidence is a successful check. Movie collection identity does not establish collection completion.'},
  'omdb-awards':{name:'OMDb awards',providers:['omdb'],scope:'All catalogue films with a valid IMDb identity.',fields:[field('awards_text','Original awards wording','Awards','movie_provider_awards'),field('wins','Reliably parsed aggregate wins','Awards','movie_provider_awards','number'),field('nominations','Reliably parsed nominations','Awards','movie_provider_awards','number')],success:'Unavailable awards or valid unquantified wording are complete checks. Unknown counts are never invented or counted as zero.'},
  'collection-rosters':{name:'collection rosters',providers:['tmdb'],scope:'Collections represented by at least two distinct canonical films in active History; all contributors count.',fields:[field('identity','TMDB collection identity','id','tmdb_collection_rosters','number',false,false),field('name','Collection name','name','tmdb_collection_rosters','text',false,false),field('roster','Complete membership roster','parts','tmdb_collection_rosters','family',false,false),field('members','Member film identities','parts.id','tmdb_collection_rosters','family',false,false),field('titles','Available member titles','parts.title','tmdb_collection_rosters','family'),field('release_dates','Available member release dates','parts.release_date','tmdb_collection_rosters','family'),field('checked_at','Successful check time','checked_at','tmdb_collection_rosters','text',false,false),field('attempt','Failed or inconclusive attempt','attempt_status','tmdb_collection_rosters')],success:'A validated full roster, including announced films, is complete evidence. Later History changes do not invalidate a successful roster; explicitly Refresh to revisit TMDB membership.'},
} as const;
const fieldGroups:Record<string,string>={"title": "Title", "year": "Release year", "original_title": "Original title", "release": "Release date", "runtime": "Runtime", "overview": "Overview", "director": "Director", "genres": "Genres", "poster": "Posters", "backdrop": "Backdrops", "original_language": "Original language", "budget": "Budget", "revenue": "Box office", "popularity": "Popularity", "tagline": "Tagline", "collection_id": "Collection membership", "collection_name": "Collection name", "awards_text": "Awards", "wins": "Wins", "nominations": "Nominations", "identity": "Franchise titles", "name": "Franchise titles", "roster": "Collection films", "members": "Collection films", "checked_at": "Check status", "attempt": "Check status", "titles": "Collection films", "release_dates": "Release dates"};
for(const [operation,contract] of Object.entries(maintenanceContract))for(const f of contract.fields){
  f.group=operation==='scores'?'9 rating types':fieldGroups[f.id] ?? ({countries:'Countries',languages:'Languages',companies:'Studios',credits:'Cast & crew',content_ratings:'Classifications',keywords:'Keywords',watch_offers:'Australian streaming',identities:'Film identities'} as Record<string,string>)[f.id] ?? f.label;
}
export const maintenanceFieldSummary=(operation:CoverageOperation)=>[...new Set(maintenanceContract[operation].fields.map(f=>f.group)),...(operation==='scores'?['Vote counts']:[])].join(' · ');
const aggregateGroups:Record<string,string>={
  '9 rating types':'Ratings',Title:'Titles','Original title':'Titles',Runtime:'Film details','Release year':'Film details','Release date':'Film details','Release dates':'Film details',Overview:'Film details',Director:'Film details',Genres:'Film details',Posters:'Artwork',Backdrops:'Artwork','Original language':'Film details',Popularity:'Film details',Tagline:'Film details',Countries:'Film details',Languages:'Film details',Studios:'Film details','Cast & crew':'Cast & crew',Classifications:'Classifications',Budget:'Financials','Box office':'Financials','Australian streaming':'Streaming',Keywords:'Keywords','Film identities':'Film identities',Awards:'Awards',Wins:'Awards',Nominations:'Awards','Collection membership':'Collections','Collection name':'Collections','Franchise titles':'Franchise membership','Collection films':'Franchise membership','Check status':'Franchise membership',
};
export const aggregateFieldSummary=()=>[...new Set(Object.keys(maintenanceContract).flatMap(operation=>maintenanceContract[operation as CoverageOperation].fields.map(f=>aggregateGroups[f.group] ?? f.group)))].join(' · ');
export const operationLevel=(operation:CoverageOperation)=>operation==='collection-rosters'?'collection':'film';
export const populateRule='Unchecked and inconclusive evidence is actionable; conclusive positive and unavailable checks remain complete regardless of age.';
export const operationInventory=(operation:CoverageOperation)=>({...maintenanceContract[operation],level:operationLevel(operation),populate:populateRule,refresh:refreshRule});
export const refreshRule='Revisit all identified eligible evidence when the provider is available.';
export type CoverageOperation=keyof typeof maintenanceContract;
export type FieldState='present'|'checked_unavailable';
export interface FieldCheck {state:FieldState;checked_at:string}
export interface OperationFieldCoverage {movie_id:string;provider:string;operation:CoverageOperation;identity_provider:string;external_id:string;fields:Record<string,FieldCheck>}
export function collectedFieldStates(operation:CoverageOperation,values:Record<string,unknown>):Record<string,FieldState>{
  return Object.fromEntries(maintenanceContract[operation].fields.flatMap(f=>{
    const value=values[f.id];if(value===undefined)return [];
    const usable=f.kind==='family'?Array.isArray(value)&&value.length>0:f.kind==='number'?typeof value==='number'&&Number.isFinite(value)&&value>=0&&(!f.positive||value>0):typeof value==='string'&&value.trim()!==''&&value!=='N/A';
    if(!f.optional && !usable)return [];
    if(value!==null && (f.kind==='family'?!Array.isArray(value):f.kind==='number'?typeof value!=='number'||!Number.isFinite(value)||value<0:typeof value!=='string'))return [];
    return [[f.id,usable?'present':'checked_unavailable']];
  }));
}
export const collectedDescription=(operation:CoverageOperation)=>maintenanceContract[operation].fields.map(f=>f.label).join(', ')+'.';
