-- Explicit opt-in reset, invoked ONLY with Wrangler --local by package scripts.
DELETE FROM history_audit;
DELETE FROM builder_sets;
DELETE FROM club_rotation;
DELETE FROM session_movies;
DELETE FROM import_applied_entities;
DELETE FROM sessions;
DELETE FROM cycles;
DELETE FROM seen_states;
DELETE FROM classics;
DELETE FROM classics_seed_allocations;
UPDATE rank_seed_counter SET value=0 WHERE id=1;
DELETE FROM source_scores;
DELETE FROM movie_assets;
DELETE FROM movie_external_ids;
DELETE FROM movie_genres;
DELETE FROM movies;
DELETE FROM auth_sessions;
DELETE FROM member_auth;
DELETE FROM members;
DELETE FROM seed_runs;
