import { z } from 'zod';
import { configSchema } from './workbook.ts';
import { ImportError } from './io.ts';
const id=z.string().regex(/^[a-zA-Z0-9_-]{1,100}$/), ref=z.string().regex(/^(Tracker:\d+:[2-6]|Should Watch:\d+)$/);
const year=z.number().int().min(1870).max(2200).nullable();
const external=z.object({provider:z.enum(['imdb','tmdb']),external_id:z.string()}).strict().refine(e=>e.provider==='imdb'?/^tt\d{7,10}$/.test(e.external_id):/^[1-9]\d*$/.test(e.external_id));
export const scoreSchema=z.object({provider:z.enum(['imdb','rottentomatoes','metacritic','letterboxd']),metric:z.enum(['rating','audience','critic']),raw_value:z.number().min(0).max(100),raw_scale:z.literal(100),normalized_value:z.number().min(0).max(100),vote_count:z.number().int().nonnegative().nullable(),fetched_at:z.iso.datetime().nullable(),retrieved_via:z.literal('legacy-spreadsheet'),import_key:z.string(),source_ref:ref.optional(),source_ordinal:z.number().int().positive().optional(),legacy_preferred:z.number().int().min(0).max(1).optional(),upstream_updated_at:z.iso.datetime().nullable().optional()}).strict().refine(s=>s.normalized_value===s.raw_value);
const seen=z.object({member_id:id,seen:z.number().int().min(0).max(1),updated_at:z.iso.datetime().nullable(),source_refs:z.array(ref).optional()}).strict();
const cycle=z.object({id,ordinal:z.number().int().positive(),rough_date:z.iso.date(),import_key:z.string(),source_row:z.number().int().positive()}).strict();
const event=z.object({id,cycle_id:id,event_date:z.iso.date(),date_precision:z.enum(['exact','cycle_rough']),kind:z.enum(['hosted','classics']),host_member_id:id.nullable(),cycle_slot:z.number().int().min(1).max(5),import_key:z.string(),films:z.array(z.object({movie_id:id,position:z.number().int().positive(),source_row:z.number().int().positive(),source_column:z.number().int().min(2).max(6)}).strict()).min(1)}).strict().refine(e=>e.date_precision===(e.cycle_slot===1?'exact':'cycle_rough'),'Regenerate legacy plans with slot-1 exact dates and later unknown event dates.');
const diagnostic=z.object({code:z.string(),severity:z.enum(['info','warning','review','blocker']),sheet:z.string(),row:z.number().optional(),column:z.number().optional(),detail:z.string()});
export const rawPlanSchema=z.object({version:z.literal(1),dryRun:z.literal(true),import_source:configSchema.shape.importSource,members:configSchema.shape.memberIds,cycles:z.array(cycle),events:z.array(event),movies:z.array(z.object({id,title:z.string().min(1).max(300),year,external_ids:z.array(external),source_refs:z.array(ref).min(1),provisional:z.boolean()}).strict()),source_records:z.array(z.object({source_ref:ref,title:z.string().min(1).max(300),year,imdb_id:z.string().regex(/^tt\d{7,10}$/).nullable()}).strict()),snapshotCapturedAt:z.iso.datetime().nullable(),diagnostics:z.array(diagnostic),rawWatchOrder:z.object({exactMatch:z.boolean(),computed:z.array(z.string())}).strict(),classics:z.array(z.object({movie_id:id,rank_seed:z.number().int().positive(),source_row:z.number().int().positive(),needs_identification:z.boolean(),scores:z.array(scoreSchema),seen:z.array(seen)}).strict()),reconciliation:z.array(z.object({status:z.string(),movie_ids:z.array(id),reason:z.string(),rows:z.array(z.number()).optional()}))}).strict();
export type RawPlan=z.infer<typeof rawPlanSchema>;
export const overridesSchema=z.object({version:z.literal(1),assignments:z.array(z.object({source_refs:z.array(ref).min(1),identity:id,tmdb_id:z.string().regex(/^[1-9]\d*$/).optional(),preferred_score_ref:ref.optional()}).strict()).default([]),seen:z.array(z.object({source_ref:ref,member_id:id,seen:z.number().int().min(0).max(1)}).strict()).default([])}).strict();
export type Overrides=z.infer<typeof overridesSchema>;
export const resolvedPlanSchema=z.object({version:z.literal(2),schemaMigration:z.literal('0004_import_provenance.sql'),import_source:configSchema.shape.importSource,members:configSchema.shape.memberIds,snapshotCapturedAt:z.iso.datetime().nullable(),movies:z.array(z.object({id,title:z.string().min(1).max(300),year,external_ids:z.array(external),source_refs:z.array(ref).min(1),identity_status:z.enum(['confirmed','provisional','ambiguous'])}).strict()),cycles:z.array(cycle),events:z.array(event),classics:z.array(z.object({movie_id:id,rank_seed:z.number().int().positive(),source_refs:z.array(ref).min(1),scores:z.array(scoreSchema),seen:z.array(seen),seen_observations:z.array(z.object({source_ref:ref,member_id:id,seen:z.number().int().min(0).max(1),observed_at:z.iso.datetime().nullable()}).strict())}).strict()),issues:z.array(z.object({code:z.string(),severity:z.enum(['review','blocker']),source_refs:z.array(ref),detail:z.string()}).strict()),rawWatchOrder:z.object({exactMatch:z.boolean(),computed:z.array(z.string())}).strict(),canonicalWatchOrder:z.array(z.string()),sourceCandidateRows:z.number().int().nonnegative()}).strict();
export type ResolvedPlan=z.infer<typeof resolvedPlanSchema>;
export function parseModel<T>(schema:z.ZodType<T>,value:unknown,kind:string):T { const r=schema.safeParse(value); if(!r.success) throw new ImportError(`${kind} validation failed: unsupported version or invalid fields. Regenerate the plan or correct the private overrides.`); return r.data; }
